L = {
    "cz": {
        "welcome": "Vítej v ZeddiHub CS:GO Tools", 
        "quote": "Nástroj pro perfektní a rychlou správu tvého CS:GO serveru!",
        "main_menu": "HLAVNÍ MENU", 
        "m_player": "Hráčské Nástroje",
        "m_server": "Serverové Nástroje",
        "m_settings": "Nastavení a Reset", 
        "m_credits": "Credits a Odkazy", 
        "m_exit": "Návrat do Launcheru", 
        "d_player": "Crosshair Generátor, Viewmodel Generátor, Config Editor.",
        "d_server": "Editor Databases.cfg, SourceMod Překladač frází.",
        "d_settings": "Cesty k souborům, Tovární Reset, Auto-Zálohování.",
        "d_credits": "Web, Discord, ZeddiS.",
        "wiz_title": "PRVOTNÍ INSTALACE CS:GO TOOLS", 
        "wiz_step1": "KROK 1: JAZYK APLIKACE",
        "wiz_step2": "KROK 2: ZDROJOVÁ SLOŽKA (Kde se nachází cfg a překlady)", 
        "wiz_step3": "KROK 3: CÍLOVÁ SLOŽKA (Kam ukládat hotové soubory)",
        "dlg_src": "Vyberte složku s původními soubory serveru", 
        "dlg_tgt": "Vyberte cílovou složku pro uložení upravených souborů",
        "use_def": "Použít výchozí složky (Doporučeno)", 
        "retry": "Zkusit vybrat znovu",
        "footer": "[W/S] Pohyb | [D/Enter] Vybrat | [A/Esc] Zpět", 
        "yes": "ANO", 
        "no": "NE", 
        "exit_q_title": "OPRAVDU CHCETE OPUSTIT CS:GO TOOLS?", 
        "reset_def": "Tovární Reset a smazání configu"
    },
    "en": {
        "welcome": "Welcome to ZeddiHub CS:GO Tools", 
        "quote": "Professional tool for managing your CS:GO server!",
        "main_menu": "MAIN MENU", 
        "m_player": "Player Tools",
        "m_server": "Server Tools",
        "m_settings": "Settings & Reset", 
        "m_credits": "Credits & Links", 
        "m_exit": "Return to Launcher", 
        "d_player": "Crosshair Generator, Viewmodel Generator, Config Editor.",
        "d_server": "Databases.cfg Editor, SourceMod Translator.",
        "d_settings": "Paths, UI language, Factory Reset, Auto-Backup.",
        "d_credits": "Web, Discord, ZeddiS.",
        "wiz_title": "ZEDDIHUB CS:GO TOOLS FIRST SETUP", 
        "wiz_step1": "STEP 1: UI LANGUAGE",
        "wiz_step2": "STEP 2: SOURCE FOLDER", 
        "wiz_step3": "STEP 3: TARGET FOLDER",
        "dlg_src": "Select folder with original server files", 
        "dlg_tgt": "Select target folder to save edited files",
        "use_def": "Use default folders", 
        "retry": "Try selecting again",
        "footer": "[W/S] Move | [D/Enter] Select | [A/Esc] Back", 
        "yes": "YES", 
        "no": "NO", 
        "exit_q_title": "DO YOU REALLY WANT TO EXIT?", 
        "reset_def": "Factory Reset and clear config"
    }
}