<script lang="ts">
  import { Save } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Card from "$components/ui/Card.svelte";
  import EntryRow from "$components/form/EntryRow.svelte";
  import { saveCfgFile } from "$api/saveFile";

  // Schema mirrors legacy `categories` dict in cs2.py:_build_autoexec
  // Each entry: [cvar, label, default]
  const CATEGORIES: { title: string; fields: [string, string, string][] }[] = [
    {
      title: "Síť (sub-tick)",
      fields: [
        ["rate", "Rate", "786432"],
        ["cl_cmdrate", "Cmdrate", "128"],
        ["cl_updaterate", "Updaterate", "128"],
        ["cl_interp_ratio", "Interp ratio", "1"],
        ["cl_interp", "Interp", "0.015625"],
        ["engine_low_latency_sleep_after_client_tick", "Low latency sleep", "1"],
      ],
    },
    {
      title: "FPS a Grafika",
      fields: [
        ["fps_max", "FPS max", "0"],
        ["fps_max_tools", "FPS max tools", "120"],
        ["r_drawtracers_firstperson", "Tracery 1st", "0"],
        ["cl_forcepreload", "Force preload", "1"],
      ],
    },
    {
      title: "Zvuk",
      fields: [
        ["snd_voipvolume", "VOIP hlasitost", "0.5"],
        ["snd_musicvolume", "Hudba", "0"],
        ["volume", "Hlasitost", "0.5"],
      ],
    },
    {
      title: "Myš",
      fields: [
        ["sensitivity", "Citlivost", "1.0"],
        ["zoom_sensitivity_ratio", "Zoom cit.", "1.0"],
      ],
    },
    {
      title: "Matchmaking",
      fields: [
        ["cl_join_advertise", "Join advertise", "2"],
        ["mm_dedicated_search_maxping", "Max ping MM", "50"],
      ],
    },
    {
      title: "Utilita",
      fields: [
        ["gameinstructor_enable", "Game instructor", "0"],
        ["cl_autohelp", "Auto help", "0"],
        ["con_enable", "Console", "1"],
      ],
    },
  ];

  // Build initial values map from defaults
  let values = $state<Record<string, string>>({});
  for (const cat of CATEGORIES) {
    for (const [k, _l, def] of cat.fields) {
      values[k] = def;
    }
  }
  let custom = $state(`// Přidejte vlastní příkazy zde\n// Příklad: bind f3 "toggle cl_righthand"\n`);
  let saveStatus = $state("");

  async function saveCfg() {
    saveStatus = "";
    let content = "// CS2 Autoexec - Generated by ZeddiHub Tools\n// https://zeddihub.eu\n\n";
    for (const cat of CATEGORIES) {
      for (const [k] of cat.fields) {
        content += `${k} "${values[k]}"\n`;
      }
    }
    const trimmed = custom.trim();
    if (trimmed && !trimmed.startsWith("//")) {
      content += `\n// Vlastní příkazy\n${trimmed}\n`;
    }
    content += `\n\necho "ZeddiHub autoexec loaded!"\nhost_writeconfig\n`;

    try {
      const path = await saveCfgFile(content, {
        defaultName: "cs2_autoexec.cfg",
        title: "Uložit autoexec.cfg",
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">CS2 — Autoexec Config</h3>
  <p class="text-xs text-zh-text-muted mb-3">Defaultní hodnoty z pro player setupů.</p>

  <div class="space-y-3">
    {#each CATEGORIES as cat}
      <Card>
        <h3 class="text-sm font-bold text-zh-primary mb-2">{cat.title}</h3>
        {#each cat.fields as [k, label, _def]}
          <EntryRow
            label={`${label} (${k})`}
            bind:value={values[k]}
          />
        {/each}
      </Card>
    {/each}

    <Card>
      <h3 class="text-sm font-bold text-zh-primary mb-2">Vlastní příkazy</h3>
      <textarea
        bind:value={custom}
        rows="6"
        spellcheck="false"
        class="w-full bg-zh-card-hover border border-zh-border rounded-entry px-3 py-2 text-xs font-mono leading-relaxed focus:outline-none focus:border-zh-primary resize-y"
      ></textarea>
    </Card>
  </div>

  <Button variant="primary" onclick={saveCfg} class="w-full mt-4">
    <Save size={14} />
    Uložit autoexec.cfg
  </Button>

  {#if saveStatus}
    <div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>
  {/if}
</div>
