<script lang="ts">
  import { Save, Copy, RefreshCw } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Card from "$components/ui/Card.svelte";
  import EntryRow from "$components/form/EntryRow.svelte";
  import Stepper from "$components/form/Stepper.svelte";
  import Dropdown from "$components/form/Dropdown.svelte";
  import BoolToggle from "$components/form/BoolToggle.svelte";
  import { saveCfgFile } from "$api/saveFile";
  import { writeText } from "@tauri-apps/plugin-clipboard-manager";

  // Reactive state for every cl_ var, mirroring legacy/gui/panels/cs2.py:_xhair_vars
  let cl_crosshairstyle             = $state("4");
  let cl_crosshaircolor              = $state("1");
  let cl_crosshairsize               = $state("2");
  let cl_crosshairthickness          = $state("0.5");
  let cl_crosshairgap                = $state("-1");
  let cl_crosshair_outlinethickness  = $state("1");
  let cl_crosshairalpha              = $state("255");
  let cl_crosshairdot                = $state("0");
  let cl_crosshair_drawoutline       = $state("1");
  let cl_crosshair_t                 = $state("0");

  let canvas: HTMLCanvasElement | null = $state(null);
  let saveStatus = $state("");

  const COLOR_MAP = ["#dd3333", "#33dd33", "#dddd33", "#3333ff", "#33dddd", "#ffffff"];

  function draw() {
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const W = canvas.width;
    const H = canvas.height;
    ctx.clearRect(0, 0, W, H);
    // Match panel background
    ctx.fillStyle = "rgb(var(--zh-card-bg))";
    ctx.fillRect(0, 0, W, H);

    const cx = W >> 1;
    const cy = H >> 1;

    const size = Math.max(0, parseInt(cl_crosshairsize) || 0);
    const gap  = parseInt(cl_crosshairgap) || 0;
    const thickness = Math.max(1, Math.round(parseFloat(cl_crosshairthickness) * 3));
    const dot = parseInt(cl_crosshairdot) === 1;
    const colorIdx = parseInt(cl_crosshaircolor);
    const tShape = parseInt(cl_crosshair_t) === 1;
    const outline = parseInt(cl_crosshair_drawoutline) === 1;

    const color = COLOR_MAP[colorIdx] ?? "#33dd33";

    const scale = 4;
    const halfT = thickness >> 1;
    const g = Math.max(0, gap * scale);
    const s = Math.max(2, size * scale);

    if (outline) {
      const oc = "#000000";
      const ow = 2;
      ctx.fillStyle = oc;
      if (!tShape) {
        // Top
        ctx.fillRect(cx - halfT - ow, cy - g - s - ow, halfT * 2 + 1 + ow * 2, s + ow * 2);
      }
      // Bottom
      ctx.fillRect(cx - halfT - ow, cy + g - ow, halfT * 2 + 1 + ow * 2, s + ow * 2);
      // Left
      ctx.fillRect(cx - g - s - ow, cy - halfT - ow, s + ow * 2, halfT * 2 + 1 + ow * 2);
      // Right
      ctx.fillRect(cx + g - ow, cy - halfT - ow, s + ow * 2, halfT * 2 + 1 + ow * 2);
    }

    ctx.fillStyle = color;
    if (!tShape) {
      ctx.fillRect(cx - halfT, cy - g - s, halfT * 2 + 1, s);
    }
    ctx.fillRect(cx - halfT, cy + g, halfT * 2 + 1, s);
    ctx.fillRect(cx - g - s, cy - halfT, s, halfT * 2 + 1);
    ctx.fillRect(cx + g, cy - halfT, s, halfT * 2 + 1);

    if (dot) {
      ctx.beginPath();
      ctx.arc(cx + 0.5, cy + 0.5, 2.5, 0, Math.PI * 2);
      ctx.fill();
    }
  }

  // Auto-redraw on any state change
  $effect(() => {
    // Touch every reactive var so the effect re-runs.
    void cl_crosshairstyle; void cl_crosshaircolor; void cl_crosshairsize;
    void cl_crosshairthickness; void cl_crosshairgap;
    void cl_crosshair_outlinethickness; void cl_crosshairalpha;
    void cl_crosshairdot; void cl_crosshair_drawoutline; void cl_crosshair_t;
    draw();
  });

  function buildVars(): Record<string, string> {
    return {
      cl_crosshairstyle,
      cl_crosshaircolor,
      cl_crosshairsize,
      cl_crosshairthickness,
      cl_crosshairgap,
      cl_crosshair_outlinethickness,
      cl_crosshairalpha,
      cl_crosshairdot,
      cl_crosshair_drawoutline,
      cl_crosshair_t,
    };
  }

  async function saveCfg() {
    saveStatus = "";
    const vars = buildVars();
    let content = "// CS2 Crosshair - Generated by ZeddiHub Tools\n// https://zeddihub.eu\n\n";
    for (const [k, v] of Object.entries(vars)) {
      content += `${k} "${v}"\n`;
    }
    try {
      const path = await saveCfgFile(content, {
        defaultName: "cs2_crosshair.cfg",
        title: "Uložit crosshair.cfg",
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }

  async function copyShareCode() {
    saveStatus = "";
    const code = Object.entries(buildVars())
      .map(([k, v]) => `${k} ${v}`)
      .join("; ");
    try {
      await writeText(code);
      saveStatus = "✓ Share kód zkopírován do schránky";
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div class="grid grid-cols-1 lg:grid-cols-[1fr_280px] gap-4">
  <!-- Form -->
  <div>
    <h3 class="text-lg font-bold text-zh-primary mb-1">CS2 — Crosshair Generátor</h3>
    <p class="text-xs text-zh-text-muted mb-3">Nastavte parametry a vygenerujte .cfg soubor.</p>

    <Card>
      <Dropdown bind:value={cl_crosshairstyle} label="Styl"
        options={[
          { value: "0", label: "0 — Default" },
          { value: "1", label: "1 — Static" },
          { value: "2", label: "2 — Classic" },
          { value: "3", label: "3 — CS:GO" },
          { value: "4", label: "4 — Small" },
          { value: "5", label: "5 — Tiny" },
        ]}
      />
      <Dropdown bind:value={cl_crosshaircolor} label="Barva"
        options={[
          { value: "0", label: "0 — Červená" },
          { value: "1", label: "1 — Zelená" },
          { value: "2", label: "2 — Žlutá" },
          { value: "3", label: "3 — Modrá" },
          { value: "4", label: "4 — Cyan" },
          { value: "5", label: "5 — Custom" },
        ]}
      />
      <Stepper bind:value={cl_crosshairsize}              label="Velikost"     min={0}  max={10}  step={0.5} hint="0–10" />
      <Stepper bind:value={cl_crosshairthickness}         label="Tloušťka"     min={0}  max={3}   step={0.5} hint="0–3" />
      <Stepper bind:value={cl_crosshairgap}               label="Mezera"       min={-10} max={10} step={1}   hint="záporná = menší" />
      <Stepper bind:value={cl_crosshair_outlinethickness} label="Tl. obrysu"   min={0}  max={3}   step={0.5} hint="0–3" />
      <Stepper bind:value={cl_crosshairalpha}             label="Průhlednost"  min={0}  max={255} step={10}  hint="0–255" />
      <BoolToggle bind:value={cl_crosshairdot}            label="Tečka"           hint="0 = Ne / 1 = Ano" />
      <BoolToggle bind:value={cl_crosshair_drawoutline}   label="Obrys"           hint="0 = Ne / 1 = Ano" />
      <BoolToggle bind:value={cl_crosshair_t}             label="T-shape"         hint="0 = Ne / 1 = Ano" />
    </Card>

    <div class="flex gap-2 mt-3">
      <Button variant="primary" onclick={saveCfg} class="flex-1">
        <Save size={14} />
        Uložit crosshair.cfg
      </Button>
      <Button variant="secondary" onclick={copyShareCode}>
        <Copy size={14} />
        Kopírovat share kód
      </Button>
    </div>

    {#if saveStatus}
      <div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>
    {/if}
  </div>

  <!-- Preview -->
  <div>
    <Card padding={4}>
      <div class="text-xs text-zh-text-muted text-center mb-2">Náhled</div>
      <div class="flex justify-center">
        <canvas bind:this={canvas} width={240} height={180} class="rounded-entry bg-zh-card-bg"></canvas>
      </div>
      <Button variant="ghost" onclick={draw} class="!h-7 text-[11px] w-full mt-2">
        <RefreshCw size={11} />
        Aktualizovat
      </Button>
    </Card>
  </div>
</div>
