<script lang="ts">
  import { Save } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Card from "$components/ui/Card.svelte";
  import { saveCfgFile } from "$api/saveFile";

  // Mirror legacy modes dict in cs2.py:_build_gamemode
  const MODES: { name: string; cmds: Record<string, string> }[] = [
    {
      name: "Competitive 5v5",
      cmds: { game_mode: "1", game_type: "0", mp_maxrounds: "24", mp_roundtime: "1.92", mp_freezetime: "15", mp_buytime: "20", mp_startmoney: "800" },
    },
    {
      name: "Competitive MR12 (Premier)",
      cmds: { game_mode: "1", game_type: "0", mp_maxrounds: "24", mp_roundtime: "1.92", mp_freezetime: "15", mp_buytime: "20", mp_startmoney: "800", mp_overtime_enable: "1", mp_overtime_maxrounds: "6" },
    },
    {
      name: "Wingman 2v2",
      cmds: { game_mode: "2", game_type: "0", mp_maxrounds: "16", mp_roundtime: "1.5", mp_freezetime: "10", mp_buytime: "15", mp_startmoney: "800" },
    },
    {
      name: "Deathmatch",
      cmds: { game_mode: "2", game_type: "1", mp_roundtime: "10", mp_freezetime: "0", mp_buytime: "0", mp_startmoney: "65535", sv_infinite_ammo: "2", mp_respawn_on_death_ct: "1", mp_respawn_on_death_t: "1" },
    },
    {
      name: "Casual",
      cmds: { game_mode: "0", game_type: "0", mp_maxrounds: "15", mp_roundtime: "2.25", mp_freezetime: "10", mp_buytime: "30", mp_startmoney: "1000" },
    },
    {
      name: "Retake",
      cmds: { game_mode: "0", game_type: "0", mp_maxrounds: "8", mp_roundtime: "0.92", mp_freezetime: "3", mp_buytime: "0", mp_startmoney: "0", sv_enablebunnyhopping: "1" },
    },
    {
      name: "1v1 Arena",
      cmds: { game_mode: "1", game_type: "0", mp_maxrounds: "16", mp_roundtime: "1.5", mp_freezetime: "5", mp_buytime: "0", mp_startmoney: "16000", mp_teammates_are_enemies: "0" },
    },
  ];

  let saveStatus = $state("");

  async function saveMode(name: string, cmds: Record<string, string>) {
    saveStatus = "";
    const safe = name.toLowerCase().replace(/ /g, "_").replace(/[()]/g, "");
    let content = `// CS2 Gamemode: ${name}\n// Generated by ZeddiHub Tools\n\n`;
    for (const [k, v] of Object.entries(cmds)) {
      content += `${k} ${v}\n`;
    }
    content += `\necho "[ZeddiHub] Gamemode ${name} loaded!"\n`;
    try {
      const path = await saveCfgFile(content, {
        defaultName: `cs2_gamemode_${safe}.cfg`,
        title: `Uložit ${name}`,
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">CS2 — Gamemode Presety</h3>
  <p class="text-xs text-zh-text-muted mb-4">7 přednastavených módů — klik na „Generovat" uloží příslušný cfg.</p>

  <div class="space-y-2">
    {#each MODES as m}
      <Card>
        <div class="flex items-center gap-3">
          <div class="flex-1 min-w-0">
            <div class="font-semibold text-zh-accent text-base">{m.name}</div>
            <div class="text-[10px] text-zh-text-muted font-mono leading-tight mt-0.5 truncate">
              {Object.entries(m.cmds).slice(0, 4).map(([k, v]) => `${k}=${v}`).join("  ")}
              {Object.keys(m.cmds).length > 4 ? "  …" : ""}
            </div>
          </div>
          <Button variant="primary" onclick={() => saveMode(m.name, m.cmds)}>
            <Save size={14} />
            Generovat
          </Button>
        </div>
      </Card>
    {/each}
  </div>

  {#if saveStatus}
    <div class="mt-3 text-xs text-zh-text-muted">{saveStatus}</div>
  {/if}
</div>
