<script lang="ts">
  import { Plus, Minus, Save, Map as MapIcon } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Card from "$components/ui/Card.svelte";
  import { saveCfgFile } from "$api/saveFile";

  type Pool = "Active Duty" | "Wingman" | "Deathmatch" | "Custom";

  // Mirror legacy _map_pools in cs2.py
  let pools = $state<Record<Pool, string[]>>({
    "Active Duty": ["de_dust2", "de_mirage", "de_inferno", "de_nuke", "de_overpass", "de_ancient", "de_anubis"],
    "Wingman":     ["de_inferno", "de_overpass", "de_vertigo", "de_nuke"],
    "Deathmatch":  ["de_dust2", "de_mirage", "de_inferno", "de_nuke", "cs_office"],
    "Custom":      [],
  });

  let activePool = $state<Pool>("Active Duty");
  let newMap = $state("");
  let selectedIdx = $state<number | null>(null);
  let saveStatus = $state("");

  function addMap() {
    const m = newMap.trim();
    if (!m) return;
    pools[activePool] = [...pools[activePool], m];
    newMap = "";
  }
  function removeSelected() {
    if (selectedIdx === null) return;
    pools[activePool] = pools[activePool].filter((_, i) => i !== selectedIdx);
    selectedIdx = null;
  }

  async function saveMapgroup() {
    saveStatus = "";
    const maps = pools[activePool];
    if (!maps.length) {
      saveStatus = "✗ Pool je prázdný";
      return;
    }
    const safe = activePool.toLowerCase().replace(/ /g, "_");
    let content = `// CS2 Map Group: ${activePool}\n// Generated by ZeddiHub Tools\n\n`;
    content += `"cs2_mapgroup_${safe}"\n{\n`;
    for (const m of maps) {
      content += `\t"${m}"\t""\n`;
    }
    content += "}\n";
    try {
      const path = await saveCfgFile(content, {
        defaultName: `cs2_mapgroup_${safe}.txt`,
        title: `Uložit mapgroup_${safe}.txt`,
        filters: [
          { name: "Text", extensions: ["txt"] },
          { name: "All", extensions: ["*"] },
        ],
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">CS2 — Map Group Editor</h3>
  <p class="text-xs text-zh-text-muted mb-3">Definuj map pool pro server.</p>

  <div class="grid grid-cols-1 md:grid-cols-[240px_1fr] gap-4">
    <!-- Pools -->
    <Card>
      <h4 class="text-xs uppercase tracking-wider text-zh-text-muted mb-2 flex items-center gap-1.5">
        <MapIcon size={12} />
        Map Pools
      </h4>
      <div class="space-y-1">
        {#each Object.keys(pools) as p}
          {@const isActive = activePool === p}
          <label class="flex items-center gap-2 px-2 py-1.5 rounded text-sm cursor-pointer hover:bg-zh-card-hover transition">
            <input
              type="radio"
              name="pool"
              value={p}
              checked={isActive}
              onchange={() => { activePool = p as Pool; selectedIdx = null; }}
              class="accent-zh-primary"
            />
            <span class:text-zh-primary={isActive}>{p}</span>
            <span class="ml-auto text-[10px] text-zh-text-muted">{pools[p as Pool].length}</span>
          </label>
        {/each}
      </div>
    </Card>

    <!-- Map list -->
    <Card>
      <h4 class="text-xs uppercase tracking-wider text-zh-text-muted mb-2">Mapy v poolu</h4>
      <div class="bg-zh-card-hover rounded-entry h-56 overflow-auto font-mono text-sm border border-zh-border">
        {#if pools[activePool].length === 0}
          <div class="px-3 py-6 text-center text-zh-text-muted text-xs">Pool je prázdný</div>
        {:else}
          {#each pools[activePool] as m, i}
            {@const isSel = selectedIdx === i}
            <button
              type="button"
              class="w-full text-left px-3 py-1 hover:bg-zh-border transition"
              class:bg-zh-primary={isSel}
              class:text-zh-text-dark={isSel}
              onclick={() => (selectedIdx = i)}
            >
              {m}
            </button>
          {/each}
        {/if}
      </div>

      <div class="flex gap-2 mt-3">
        <input
          type="text"
          bind:value={newMap}
          placeholder="de_mapname nebo workshop/ID"
          class="flex-1 bg-zh-card-hover border border-zh-border rounded-entry px-3 h-9 text-sm font-mono focus:outline-none focus:border-zh-primary"
          onkeydown={(e) => { if (e.key === "Enter") { e.preventDefault(); addMap(); }}}
        />
        <Button variant="primary" onclick={addMap}>
          <Plus size={14} />
          Přidat
        </Button>
        <Button variant="secondary" onclick={removeSelected} disabled={selectedIdx === null}>
          <Minus size={14} />
          Odebrat
        </Button>
      </div>

      <Button variant="primary" onclick={saveMapgroup} class="w-full mt-3">
        <Save size={14} />
        Generovat mapgroup
      </Button>

      {#if saveStatus}
        <div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>
      {/if}
    </Card>
  </div>
</div>
