<script lang="ts">
  import { Save } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Card from "$components/ui/Card.svelte";
  import EntryRow from "$components/form/EntryRow.svelte";
  import { saveCfgFile } from "$api/saveFile";

  // Mirror legacy practice_defs from cs2.py:_build_practice
  const FIELDS: [string, string, string][] = [
    ["sv_cheats", "SV Cheats (nutné)", "1"],
    ["sv_infinite_ammo", "Nekonečná munice", "1"],
    ["mp_buy_anywhere", "Kupovat kdekoliv", "1"],
    ["mp_buytime", "Buy time", "99999"],
    ["mp_freezetime", "Freeze time", "0"],
    ["mp_roundtime_defuse", "Round time (min)", "60"],
    ["mp_roundtime", "Round time alt", "60"],
    ["mp_maxmoney", "Max peníze", "65535"],
    ["mp_startmoney", "Start peníze", "65535"],
    ["sv_grenade_trajectory_prac_pipreview", "Nade trajektorie", "1"],
    ["sv_grenade_trajectory_prac_trailtime", "Nade trail time", "4"],
    ["cl_grenadepreview", "Grenade preview", "1"],
  ];

  let values = $state<Record<string, string>>({});
  for (const [k, _l, def] of FIELDS) values[k] = def;
  let saveStatus = $state("");

  async function saveCfg() {
    saveStatus = "";
    let content = "// CS2 Practice Mode - Generated by ZeddiHub Tools\n";
    content += "// Použijte: exec cs2_practice\n\n";
    content += "mp_warmup_end\nbot_kick\n\n";
    for (const [k] of FIELDS) {
      content += `${k} ${values[k]}\n`;
    }
    content += "\nmp_restartgame 1\necho \"Practice mode activated!\"\n";

    try {
      const path = await saveCfgFile(content, {
        defaultName: "cs2_practice.cfg",
        title: "Uložit practice.cfg",
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">CS2 — Practice Config</h3>
  <p class="text-xs text-zh-text-muted mb-3">Pro trénink granátů, nákupy kdekoliv, nekonečná munice…</p>

  <Card>
    <h3 class="text-sm font-bold text-zh-primary mb-2">Nastavení</h3>
    {#each FIELDS as [k, label, _def]}
      <EntryRow label={label} bind:value={values[k]} hint={k} />
    {/each}
  </Card>

  <Button variant="primary" onclick={saveCfg} class="w-full mt-3">
    <Save size={14} />
    Uložit practice.cfg
  </Button>

  {#if saveStatus}
    <div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>
  {/if}
</div>
