L = {
    "cz": {
        "welcome": "Vítej v ZeddiHub Rust Editoru", 
        "quote": "Profesionální nástroj pro opravy, kompilace a analýzy!",
        "main_menu": "HLAVNÍ MENU", 
        "m_fix_menu": "Nástroje pro Opravu Pluginů", 
        "m_check": "Analyzátor Stability a Chyb", 
        "m_cmd_ext": "Extraktor Příkazů Pluginu",
        "m_sim_data": "Simulátor Vygenerovaných Souborů",
        "m_compiler": "Simulátor Oxide Kompilátoru",
        "m_folders": "Přehled Cílové Složky",
        "m_settings": "Nastavení a Reset", 
        "m_credits": "Credits a Odkazy", 
        "m_exit": "Návrat do Launcheru", 
        "m_back": "Zpět do Hlavního menu",
        "d_fix_menu": "Hromadné opravy, úprava příkazů a překlady (ukládá se do fronty).",
        "d_check": "Proskenuje kód, najde chybějící závorky a upozorní na náročné funkce.",
        "d_cmd_ext": "Najde a vypíše všechny Console a Chat příkazy z pluginů.",
        "d_sim_data": "Zjistí, jaké datové a konfigurační soubory plugin na serveru vytvoří.",
        "d_compiler": "Zkompiluje vybrané pluginy v paměti a krásně vypíše errory.",
        "d_folders": "Prohlížení a čtení opravených pluginů přímo v konzoli.",
        "d_settings": "Cesty, UI jazyk, akce po dokončení a Tovární Reset.",
        "d_credits": "Web, Discord, Verze.",
        "wiz_title": "PRVOTNÍ INSTALACE ZEDDIHUB EDITORU", 
        "wiz_step1": "KROK 1: JAZYK APLIKACE",
        "wiz_step2": "KROK 2: ZDROJOVÁ SLOŽKA (Rozbité pluginy)", 
        "wiz_step3": "KROK 3: CÍLOVÁ SLOŽKA (Opravené pluginy)",
        "wiz_step4": "KROK 4: AKCE PO DOKONČENÍ ÚLOHY",
        "wiz_step5": "KROK 5: AUTOMATICKÁ KOMPILACE",
        "wiz_step6": "KROK 6: OTEVÍRÁNÍ SLOŽKY",
        "dlg_src": "Vyberte složku s původními pluginy", 
        "dlg_tgt": "Vyberte složku pro uložení opravených pluginů",
        "use_def": "Použít výchozí složky (Doporučeno)", 
        "retry": "Zkusit vybrat znovu",
        "footer": "[W/S] Pohyb | [D/Enter] Vybrat | [A/Esc] Zpět", 
        "yes": "ANO", "no": "NE", 
        "abort": "AKCE BYLA ZRUŠENA UŽIVATELEM.", 
        "exit_q_title": "OPRAVDU CHCETE OPUSTIT EDITOR?", 
        "restarting": "RESTARTUJI EDITOR DO VÝCHOZÍHO NASTAVENÍ...", 
        "no_files": "Žádné .cs soubory nenalezeny!", 
        "src_not_exist": "Zdrojová složka neexistuje!",
        "post_action": "Po dokončení", 
        "reset_def": "Tovární Reset a smazání configu"
    },
    "en": {
        "welcome": "Welcome to ZeddiHub Rust Editor", 
        "quote": "Professional tool for fixing, compiling and analyzing!",
        "main_menu": "MAIN MENU", 
        "m_fix_menu": "Plugin Fix Tools", 
        "m_check": "Stability & Error Analyzer", 
        "m_cmd_ext": "Plugin Command Extractor",
        "m_sim_data": "Generated Files Simulator",
        "m_compiler": "Oxide Compiler Simulator",
        "m_folders": "Target Folder Overview",
        "m_settings": "Settings & Reset", 
        "m_credits": "Credits & Links", 
        "m_exit": "Return to Launcher", 
        "m_back": "Back to Main Menu",
        "d_fix_menu": "Bulk fixes, command editing and translations (added to queue).",
        "d_check": "Scans code for missing brackets and heavy functions.",
        "d_cmd_ext": "Finds and lists all Console and Chat commands from plugins.",
        "d_sim_data": "Finds out what config/data files the plugin will create.",
        "d_compiler": "Dry-compiles selected plugins in memory and shows C# errors.",
        "d_folders": "Browse and read fixed plugins directly in console.",
        "d_settings": "Paths, UI language, post-actions and Factory Reset.",
        "d_credits": "Web, Discord, Version.",
        "wiz_title": "ZEDDIHUB EDITOR FIRST SETUP", 
        "wiz_step1": "STEP 1: UI LANGUAGE",
        "wiz_step2": "STEP 2: SOURCE FOLDER (Broken plugins)", 
        "wiz_step3": "STEP 3: TARGET FOLDER (Fixed plugins)",
        "wiz_step4": "STEP 4: ACTION AFTER COMPLETION",
        "wiz_step5": "STEP 5: AUTOMATIC COMPILATION",
        "wiz_step6": "STEP 6: OPEN FOLDER",
        "dlg_src": "Select folder with original plugins", 
        "dlg_tgt": "Select folder to save fixed plugins",
        "use_def": "Use default folders (Recommended)", 
        "retry": "Try selecting again",
        "footer": "[W/S] Move | [D/Enter] Select | [A/Esc] Back", 
        "yes": "YES", "no": "NO", 
        "abort": "ACTION ABORTED.", 
        "exit_q_title": "DO YOU REALLY WANT TO EXIT?", 
        "restarting": "RESTARTING TO DEFAULT SETTINGS...", 
        "no_files": "No .cs files found!", 
        "src_not_exist": "Source folder does not exist!",
        "post_action": "After completion", 
        "reset_def": "Factory Reset and clear config"
    }
}