"""
ZeddiHub Tools - Color theme system per game.

v1.8.0 — "Blur" redesign:
* Deeper, richer blacks with subtle blue undertone for the default theme
* Enhanced card surfaces with layered "glass" feel (card_bg + card_hover + glass)
* Brighter, more saturated accents for punchy highlights
* Improved text hierarchy (text / text_dim / text_dark / text_muted)
* New helper keys: `glass`, `outline`, `accent_soft`, `shadow` so new widgets
  can adopt the modern look without breaking existing panels.
"""

GAME_THEMES = {
    "default": {
        "primary": "#f5b623",
        "primary_hover": "#e6a714",
        "bg": "#0a0a0d",
        "sidebar_bg": "#101015",
        "header_bg": "#0b0b10",
        "content_bg": "#0d0d12",
        "card_bg": "#16161c",
        "card_hover": "#1f1f28",
        "glass": "#1a1a22",
        "secondary": "#1e1e26",
        "border": "#2a2a36",
        "outline": "#3a3a48",
        "text": "#f4f4f6",
        "text_dim": "#9a9aa6",
        "text_dark": "#5a5a66",
        "text_muted": "#70707c",
        "success": "#4ade80",
        "error": "#f87171",
        "warning": "#fb923c",
        "accent": "#f5b623",
        "accent_soft": "#3a2c10",
        "shadow": "#050508",
        "button_fg": "#ffffff",
        "name": "Default",
        # Light mode overrides
        "light": {
            "bg": "#f0f0f4",
            "sidebar_bg": "#e2e2ea",
            "header_bg": "#dadae4",
            "content_bg": "#f5f5f9",
            "card_bg": "#ffffff",
            "card_hover": "#f4f4f8",
            "glass": "#f8f8fc",
            "secondary": "#e8e8f0",
            "border": "#cacad4",
            "outline": "#b0b0be",
            "text": "#15151a",
            "text_dim": "#666672",
            "text_dark": "#8a8a96",
            "text_muted": "#7a7a86",
            "accent_soft": "#fbe8be",
            "shadow": "#d0d0d8",
        },
    },
    "cs2": {
        "primary": "#5b9cf6",
        "primary_hover": "#4a8ae0",
        "bg": "#09090f",
        "sidebar_bg": "#0f0f1c",
        "header_bg": "#0a0a13",
        "content_bg": "#0c0c17",
        "card_bg": "#151523",
        "card_hover": "#1d1d2d",
        "glass": "#181827",
        "secondary": "#1a1a28",
        "border": "#26263e",
        "outline": "#3a3a58",
        "text": "#f4f4f6",
        "text_dim": "#8a8aaa",
        "text_dark": "#545474",
        "text_muted": "#6a6a88",
        "success": "#4ade80",
        "error": "#f87171",
        "warning": "#fb923c",
        "accent": "#5b9cf6",
        "accent_soft": "#12213a",
        "shadow": "#04040a",
        "button_fg": "#ffffff",
        "name": "Counter-Strike 2",
        "light": {
            "bg": "#eef2ff",
            "sidebar_bg": "#dde4f8",
            "header_bg": "#ccd4f0",
            "content_bg": "#f0f4ff",
            "card_bg": "#ffffff",
            "card_hover": "#edf1ff",
            "glass": "#f2f5ff",
            "secondary": "#e4eafc",
            "border": "#b8c8f0",
            "outline": "#98a8d8",
            "text": "#1a1a2e",
            "text_dim": "#555577",
            "text_dark": "#888899",
            "text_muted": "#6a6a88",
            "accent_soft": "#d2e0fa",
            "shadow": "#c0c8e8",
        },
    },
    "csgo": {
        "primary": "#fbbf24",
        "primary_hover": "#e0aa10",
        "bg": "#0b0a00",
        "sidebar_bg": "#141200",
        "header_bg": "#0e0d00",
        "content_bg": "#0f0d00",
        "card_bg": "#1c1900",
        "card_hover": "#242100",
        "glass": "#1f1c00",
        "secondary": "#1a1700",
        "border": "#2e2a00",
        "outline": "#3d3800",
        "text": "#f4f4f6",
        "text_dim": "#aaa888",
        "text_dark": "#666540",
        "text_muted": "#858358",
        "success": "#4ade80",
        "error": "#f87171",
        "warning": "#fb923c",
        "accent": "#fbbf24",
        "accent_soft": "#3a2f00",
        "shadow": "#060500",
        "button_fg": "#ffffff",
        "name": "CS:GO",
        "light": {
            "bg": "#fffde8",
            "sidebar_bg": "#f5f0cc",
            "header_bg": "#ede8b8",
            "content_bg": "#fefef0",
            "card_bg": "#ffffff",
            "card_hover": "#fbf8dc",
            "glass": "#fefbe0",
            "secondary": "#f2edd8",
            "border": "#d8d0a0",
            "outline": "#b8b080",
            "text": "#1a1800",
            "text_dim": "#666540",
            "text_dark": "#999870",
            "text_muted": "#858358",
            "accent_soft": "#fbecb0",
            "shadow": "#e0dbc0",
        },
    },
    "rust": {
        "primary": "#f97316",
        "primary_hover": "#e06210",
        "bg": "#0d0a00",
        "sidebar_bg": "#161000",
        "header_bg": "#100c00",
        "content_bg": "#110d00",
        "card_bg": "#1a1200",
        "card_hover": "#221700",
        "glass": "#1d1400",
        "secondary": "#180f00",
        "border": "#2c1d00",
        "outline": "#3a2700",
        "text": "#f4f4f6",
        "text_dim": "#aa9888",
        "text_dark": "#665540",
        "text_muted": "#866f55",
        "success": "#4ade80",
        "error": "#f87171",
        "warning": "#fb923c",
        "accent": "#f97316",
        "accent_soft": "#3a1e00",
        "shadow": "#050300",
        "button_fg": "#ffffff",
        "name": "Rust",
        "light": {
            "bg": "#fff5ee",
            "sidebar_bg": "#f0e0d0",
            "header_bg": "#e8d4c0",
            "content_bg": "#fdf5f0",
            "card_bg": "#ffffff",
            "card_hover": "#fceade",
            "glass": "#fdf0e6",
            "secondary": "#f0e4d8",
            "border": "#d8c0a8",
            "outline": "#b89a80",
            "text": "#1a0e00",
            "text_dim": "#664432",
            "text_dark": "#998870",
            "text_muted": "#866f55",
            "accent_soft": "#fdd9ba",
            "shadow": "#e8d5c2",
        },
    },
}


def get_theme(game: str, mode: str = None) -> dict:
    base = dict(GAME_THEMES.get(game, GAME_THEMES["default"]))
    if mode == "light":
        light_overrides = base.pop("light", {})
        base.update(light_overrides)
    else:
        base.pop("light", None)
    return base
