"""
ZeddiHub Tools - Color theme system per game.

v2.1.0 - "Modern Premium" refresh + Claude-desktop-app aesthetic pass.
* Deeper near-black backgrounds (#0a0a0f) — content lives in whitespace,
  not in bordered boxes.
* Flat sidebar/nav — no resting background, pill-shaped active state.
* Subtle dividers (#1a1a24) replace hard borders for most UI separators.
* Borderless input fills.
* Typography tokens: text_strong (page titles), text_muted (captions).
* Card_hover for subtle interactions.

Back-compat: every pre-existing theme key is preserved. Only NEW tokens added:
    nav_hover, nav_active_bg, nav_active_text, divider, input_bg,
    card_hover (already existed), text_strong, text_muted (already existed).
"""

# Shared numeric design tokens — new in v2.1.0
_RADIUS = {
    "radius_card": 14,
    "radius_button": 10,
    "radius_entry": 8,
}

GAME_THEMES = {
    "default": {
        # Modern Premium Dark palette
        "primary": "#3b82f6",
        "primary_hover": "#60a5fa",
        "bg": "#0a0a0f",
        "sidebar_bg": "#0c0c14",
        "header_bg": "#0b0b12",
        "content_bg": "#0e0e17",
        "card_bg": "#13131a",
        "card_hover": "#181820",
        "glass": "#17171f",
        "secondary": "#1a1a24",
        "border": "#2a2a35",
        "outline": "#3a3a48",
        "divider": "#1a1a24",
        "input_bg": "#1a1a24",
        "nav_hover": "#1a1a22",
        "nav_active_bg": "#3b82f6",
        "nav_active_text": "#ffffff",
        "text": "#ececf2",
        "text_strong": "#f5f5f7",
        "text_dim": "#8a8aa3",
        "text_muted": "#7a7a90",
        "text_dark": "#0a0a0f",
        "success": "#22c55e",
        "error": "#ef4444",
        "warning": "#f59e0b",
        "accent": "#8b5cf6",
        "accent_soft": "#231a3e",
        "shadow": "",
        "button_fg": "#ffffff",
        "radius_card": 14,
        "radius_button": 10,
        "radius_entry": 8,
        "name": "Default",
        "light": {
            "bg": "#f7f7f9",
            "sidebar_bg": "#f0f0f3",
            "header_bg": "#f7f7f9",
            "content_bg": "#f7f7f9",
            "card_bg": "#ffffff",
            "card_hover": "#f2f2f5",
            "glass": "#fafafd",
            "secondary": "#e8e8ec",
            "border": "#e8e8ec",
            "outline": "#d0d0d8",
            "divider": "#e8e8ec",
            "input_bg": "#f2f2f5",
            "nav_hover": "#eeeef2",
            "nav_active_bg": "#3b82f6",
            "nav_active_text": "#ffffff",
            "text": "#0a0a0f",
            "text_strong": "#0a0a0f",
            "text_dim": "#5a5a78",
            "text_muted": "#7a7a90",
            "text_dark": "#b8b8c8",
            "accent_soft": "#e6ddf5",
            "shadow": "",
        },
    },
    "cs2": {
        "primary": "#f5b623",
        "primary_hover": "#ffca3d",
        "bg": "#0a0a0f",
        "sidebar_bg": "#0c0c14",
        "header_bg": "#0b0b12",
        "content_bg": "#0e0e17",
        "card_bg": "#13131a",
        "card_hover": "#181820",
        "glass": "#17171f",
        "secondary": "#1a1a24",
        "border": "#2a2a35",
        "outline": "#3a3a48",
        "divider": "#1a1a24",
        "input_bg": "#1a1a24",
        "nav_hover": "#1a1a22",
        "nav_active_bg": "#f5b623",
        "nav_active_text": "#0a0a0f",
        "text": "#ececf2",
        "text_strong": "#f5f5f7",
        "text_dim": "#8a8aa3",
        "text_muted": "#7a7a90",
        "text_dark": "#0a0a0f",
        "success": "#22c55e",
        "error": "#ef4444",
        "warning": "#f59e0b",
        "accent": "#8b5cf6",
        "accent_soft": "#3a2c10",
        "shadow": "",
        "button_fg": "#ffffff",
        "radius_card": 14,
        "radius_button": 10,
        "radius_entry": 8,
        "name": "Counter-Strike 2",
        "light": {
            "bg": "#f7f7f9",
            "sidebar_bg": "#f0f0f3",
            "header_bg": "#f7f7f9",
            "content_bg": "#f7f7f9",
            "card_bg": "#ffffff",
            "card_hover": "#fbf3de",
            "glass": "#fef8e8",
            "secondary": "#e8e8ec",
            "border": "#e8e8ec",
            "outline": "#d0d0d8",
            "divider": "#e8e8ec",
            "input_bg": "#f2f2f5",
            "nav_hover": "#eeeef2",
            "nav_active_bg": "#f5b623",
            "nav_active_text": "#0a0a0f",
            "text": "#0a0a0f",
            "text_strong": "#0a0a0f",
            "text_dim": "#5a5a78",
            "text_muted": "#7a7a90",
            "text_dark": "#b8b8c8",
            "accent_soft": "#fbe8be",
            "shadow": "",
        },
    },
    "csgo": {
        "primary": "#3399ff",
        "primary_hover": "#4dabff",
        "bg": "#0a0a0f",
        "sidebar_bg": "#0c0c14",
        "header_bg": "#0b0b12",
        "content_bg": "#0e0e17",
        "card_bg": "#13131a",
        "card_hover": "#181820",
        "glass": "#17171f",
        "secondary": "#1a1a24",
        "border": "#2a2a35",
        "outline": "#3a3a48",
        "divider": "#1a1a24",
        "input_bg": "#1a1a24",
        "nav_hover": "#1a1a22",
        "nav_active_bg": "#3399ff",
        "nav_active_text": "#ffffff",
        "text": "#ececf2",
        "text_strong": "#f5f5f7",
        "text_dim": "#8a8aa3",
        "text_muted": "#7a7a90",
        "text_dark": "#0a0a0f",
        "success": "#22c55e",
        "error": "#ef4444",
        "warning": "#f59e0b",
        "accent": "#8b5cf6",
        "accent_soft": "#0f2238",
        "shadow": "",
        "button_fg": "#ffffff",
        "radius_card": 14,
        "radius_button": 10,
        "radius_entry": 8,
        "name": "CS:GO",
        "light": {
            "bg": "#f7f7f9",
            "sidebar_bg": "#f0f0f3",
            "header_bg": "#f7f7f9",
            "content_bg": "#f7f7f9",
            "card_bg": "#ffffff",
            "card_hover": "#e8f1ff",
            "glass": "#f2f7ff",
            "secondary": "#e8e8ec",
            "border": "#e8e8ec",
            "outline": "#d0d0d8",
            "divider": "#e8e8ec",
            "input_bg": "#f2f2f5",
            "nav_hover": "#eeeef2",
            "nav_active_bg": "#3399ff",
            "nav_active_text": "#ffffff",
            "text": "#0a0a0f",
            "text_strong": "#0a0a0f",
            "text_dim": "#5a5a78",
            "text_muted": "#7a7a90",
            "text_dark": "#b8b8c8",
            "accent_soft": "#d2e0fa",
            "shadow": "",
        },
    },
    "rust": {
        "primary": "#cd5a3a",
        "primary_hover": "#e06a48",
        "bg": "#0a0a0f",
        "sidebar_bg": "#0c0c14",
        "header_bg": "#0b0b12",
        "content_bg": "#0e0e17",
        "card_bg": "#13131a",
        "card_hover": "#181820",
        "glass": "#17171f",
        "secondary": "#1a1a24",
        "border": "#2a2a35",
        "outline": "#3a3a48",
        "divider": "#1a1a24",
        "input_bg": "#1a1a24",
        "nav_hover": "#1a1a22",
        "nav_active_bg": "#cd5a3a",
        "nav_active_text": "#ffffff",
        "text": "#ececf2",
        "text_strong": "#f5f5f7",
        "text_dim": "#8a8aa3",
        "text_muted": "#7a7a90",
        "text_dark": "#0a0a0f",
        "success": "#22c55e",
        "error": "#ef4444",
        "warning": "#f59e0b",
        "accent": "#8b5cf6",
        "accent_soft": "#3a2010",
        "shadow": "",
        "button_fg": "#ffffff",
        "radius_card": 14,
        "radius_button": 10,
        "radius_entry": 8,
        "name": "Rust",
        "light": {
            "bg": "#f7f7f9",
            "sidebar_bg": "#f0f0f3",
            "header_bg": "#f7f7f9",
            "content_bg": "#f7f7f9",
            "card_bg": "#ffffff",
            "card_hover": "#fbeae2",
            "glass": "#fef2ec",
            "secondary": "#e8e8ec",
            "border": "#e8e8ec",
            "outline": "#d0d0d8",
            "divider": "#e8e8ec",
            "input_bg": "#f2f2f5",
            "nav_hover": "#eeeef2",
            "nav_active_bg": "#cd5a3a",
            "nav_active_text": "#ffffff",
            "text": "#0a0a0f",
            "text_strong": "#0a0a0f",
            "text_dim": "#5a5a78",
            "text_muted": "#7a7a90",
            "text_dark": "#b8b8c8",
            "accent_soft": "#fdd9ba",
            "shadow": "",
        },
    },
}


def get_theme(game: str, mode: str = None) -> dict:
    base = dict(GAME_THEMES.get(game, GAME_THEMES["default"]))
    if mode == "light":
        light_overrides = base.pop("light", {})
        base.update(light_overrides)
    else:
        base.pop("light", None)
    return base
