import os
import time
import platform
import threading
import queue
import tkinter as tk
from tkinter import filedialog
import re
from .core import *


def draw_crosshair_ascii(size, gap, thickness, color_idx, dot):
    try:
        s = max(0, int(float(size)))
        g = int(float(gap))
        th = max(1, int(float(thickness) * 2))
        has_dot = int(float(dot)) == 1
    except Exception:
        s, g, th, has_dot = 2, 0, 1, False

    colors = [RED, GREEN, YELLOW, "\033[38;5;21m", CYAN, RESET]
    try:
        c_color = colors[int(color_idx)] if 0 <= int(color_idx) <= 5 else GREEN
    except Exception:
        c_color = GREEN

    art = []
    art.append(GRAY + "+" + "-" * 30 + "+" + RESET)
    center_y, center_x = 7, 15
    for y in range(15):
        row = ""
        for x in range(30):
            is_dot = has_dot and abs(x - center_x) <= 0 and abs(y - center_y) <= 0
            is_top = center_x - (th // 2) <= x <= center_x + (th // 2) and (center_y - g - s <= y < center_y - g)
            is_bot = center_x - (th // 2) <= x <= center_x + (th // 2) and (center_y + g < y <= center_y + g + s)
            is_left = center_y - (th // 2) <= y <= center_y + (th // 2) and (center_x - g - s * 2 <= x < center_x - g)
            is_right = center_y - (th // 2) <= y <= center_y + (th // 2) and (center_x + g < x <= center_x + g + s * 2)
            if is_dot:
                row += c_color + "#" + RESET
            elif is_top or is_bot or is_left or is_right:
                row += c_color + "|" + RESET
            else:
                row += " "
        art.append(GRAY + "|" + RESET + row + GRAY + "|" + RESET)
    art.append(GRAY + "+" + "-" * 30 + "+" + RESET)
    return art


def crosshair_generator():
    settings_xhair = {
        "cl_crosshairstyle": "4",
        "cl_crosshairsize": "2",
        "cl_crosshairthickness": "0.5",
        "cl_crosshairgap": "-1",
        "cl_crosshairdot": "0",
        "cl_crosshaircolor": "1",
        "cl_crosshair_drawoutline": "1",
        "cl_crosshair_outlinethickness": "1",
        "cl_crosshairalpha": "255",
        "cl_crosshair_t": "0"
    }
    sel = 0
    while True:
        keys = list(settings_xhair.keys())
        opts = [f"{k.ljust(32)}: {settings_xhair[k]}" for k in keys]
        opts.append("")
        opts.append(GREEN + "Uložit do cs2_crosshair.cfg" + RESET)
        opts.append(CYAN + "Generovat CS2 Shareable Code" + RESET)

        art = draw_crosshair_ascii(
            settings_xhair["cl_crosshairsize"], settings_xhair["cl_crosshairgap"],
            settings_xhair["cl_crosshairthickness"], settings_xhair["cl_crosshaircolor"],
            settings_xhair["cl_crosshairdot"]
        )

        render_menu("CS2 CROSSHAIR GENERÁTOR", opts, sel,
                     footer="[W/S] Pohyb | [Enter] Upravit | [A/Esc] Zpět", extra_art=art)
        k = read_key()
        if k in ['a', 'esc', 'q']: return
        elif k == 'w' and sel > 0: sel -= 1
        elif k == 's' and sel < len(opts) - 1: sel += 1
        elif k in ['d', 'enter', 'space']:
            if opts[sel] == "": continue
            if "Uložit" in opts[sel]:
                os.makedirs(settings["target_dir"], exist_ok=True)
                path = os.path.join(settings["target_dir"], "cs2_crosshair.cfg")
                with open(path, "w", encoding="utf-8") as f:
                    f.write("// CS2 Crosshair - Generated by ZeddiHub CS2 Tools\n")
                    for kn, vv in settings_xhair.items():
                        f.write(f'{kn} "{vv}"\n')
                print_header()
                print("\n" * 4 + GREEN + center("Soubor cs2_crosshair.cfg úspěšně vygenerován!") + RESET)
                time.sleep(2)
                if settings.get("open_folder_after") and platform.system() == "Windows":
                    try: os.startfile(settings["target_dir"])
                    except Exception: pass
                return
            elif "Shareable" in opts[sel]:
                print_header()
                print("\n" * 4 + YELLOW + center("CS2 SHAREABLE CODE") + RESET)
                code_parts = [f"{k} {v}" for k, v in settings_xhair.items()]
                code = "; ".join(code_parts)
                print("\n" + CYAN + center("Zkopírujte tento příkaz do konzole CS2:") + RESET)
                print("\n" + WHITE + center(code[:90]) + RESET)
                if len(code) > 90:
                    print(WHITE + center(code[90:]) + RESET)
                print("\n" + YELLOW + center("[Enter] Zpět") + RESET)
                read_key(allow_esc_exit=False)
            else:
                c_key = keys[sel]
                print_header()
                print("\n" * 4 + YELLOW + center(f"ÚPRAVA HODNOTY: {c_key}") + RESET)
                if c_key == "cl_crosshaircolor":
                    print(center("(0=Červená, 1=Zelená, 2=Žlutá, 3=Modrá, 4=Světle modrá, 5=Vlastní)"))
                elif c_key == "cl_crosshair_t":
                    print(center("(0=Plný kříž, 1=Jen T-shape bez horní čáry)"))
                new_val = safe_input("\n" + center(f"Nová hodnota (nyní '{settings_xhair[c_key]}'): "))
                if new_val is not None and new_val.strip() != "":
                    settings_xhair[c_key] = new_val.strip()


def draw_viewmodel_ascii(fov, x, y, z):
    """Draw ASCII art viewmodel preview based on current settings."""
    try:
        fov_f = float(fov)
        x_f = float(x)
        y_f = float(y)
        z_f = float(z)
    except Exception:
        fov_f, x_f, y_f, z_f = 68.0, 2.5, 0.0, -1.5

    art = []
    w, h = 40, 14

    # Compute gun position based on offsets
    gun_x = int(w * 0.6 + x_f * 2 - (fov_f - 68) * 0.3)
    gun_y = int(h * 0.7 + z_f * 1.5)
    gun_x = max(4, min(w - 6, gun_x))
    gun_y = max(3, min(h - 2, gun_y))

    grid = [[' ' for _ in range(w)] for _ in range(h)]

    # Draw gun body (simplified rifle shape)
    barrel_len = max(3, int(8 - (fov_f - 54) * 0.1))
    for bx in range(gun_x - barrel_len, gun_x + 1):
        if 0 <= bx < w and 0 <= gun_y < h:
            grid[gun_y][bx] = '='
        if 0 <= bx < w and 0 <= gun_y - 1 < h:
            grid[gun_y - 1][bx] = '-'

    # Grip
    for gy in range(gun_y + 1, min(h, gun_y + 4)):
        if 0 <= gun_x < w:
            grid[gy][gun_x] = '|'
        if 0 <= gun_x - 1 < w:
            grid[gy][gun_x - 1] = '|'

    # Stock
    for sx in range(gun_x + 1, min(w, gun_x + 5)):
        if 0 <= gun_y < h:
            grid[gun_y][sx] = '='
        if 0 <= gun_y + 1 < h:
            grid[gun_y + 1][sx] = '_'

    # Muzzle
    if 0 <= gun_x - barrel_len - 1 < w and 0 <= gun_y < h:
        grid[gun_y][gun_x - barrel_len - 1] = '>'

    # Crosshair in center
    cx, cy = w // 2, h // 3
    if 0 <= cy < h and 0 <= cx < w:
        grid[cy][cx] = '+'

    art.append(GRAY + "+" + "-" * w + "+" + RESET)
    for row in grid:
        line = ""
        for ch in row:
            if ch in ('=', '-', '|', '_', '>'):
                line += CYAN + ch + RESET
            elif ch == '+':
                line += GREEN + ch + RESET
            else:
                line += ch
        art.append(GRAY + "|" + RESET + line + GRAY + "|" + RESET)
    art.append(GRAY + "+" + "-" * w + "+" + RESET)
    info = f"FOV:{fov_f:.0f} X:{x_f:+.1f} Y:{y_f:+.1f} Z:{z_f:+.1f}"
    art.append(DIM + GRAY + center(info, w + 2) + RESET)
    return art


def viewmodel_generator():
    settings_vm = {
        "viewmodel_fov": "68",
        "viewmodel_offset_x": "2.5",
        "viewmodel_offset_y": "0",
        "viewmodel_offset_z": "-1.5",
        "viewmodel_presetpos": "3",
        "cl_bob_lower_amt": "5",
        "cl_bobamt_lat": "0.1",
        "cl_bobamt_vert": "0.1"
    }
    sel = 0
    while True:
        keys = list(settings_vm.keys())
        opts = [f"{k.ljust(28)}: {settings_vm[k]}" for k in keys]
        opts.append("")
        opts.append(GREEN + "Uložit do cs2_viewmodel.cfg" + RESET)

        art = draw_viewmodel_ascii(
            settings_vm["viewmodel_fov"], settings_vm["viewmodel_offset_x"],
            settings_vm["viewmodel_offset_y"], settings_vm["viewmodel_offset_z"]
        )

        render_menu("CS2 VIEWMODEL GENERÁTOR (NÁHLED)", opts, sel,
                     footer="[W/S] Pohyb | [Enter] Upravit | [A/Esc] Zpět", extra_art=art)
        k = read_key()
        if k in ['a', 'esc', 'q']: return
        elif k == 'w' and sel > 0: sel -= 1
        elif k == 's' and sel < len(opts) - 1: sel += 1
        elif k in ['d', 'enter', 'space']:
            if opts[sel] == "": continue
            if "Uložit" in opts[sel]:
                os.makedirs(settings["target_dir"], exist_ok=True)
                path = os.path.join(settings["target_dir"], "cs2_viewmodel.cfg")
                with open(path, "w", encoding="utf-8") as f:
                    f.write("// CS2 Viewmodel - Generated by ZeddiHub CS2 Tools\n")
                    for kn, vv in settings_vm.items():
                        f.write(f'{kn} "{vv}"\n')
                print_header()
                print("\n" * 4 + GREEN + center("Soubor cs2_viewmodel.cfg úspěšně vygenerován!") + RESET)
                time.sleep(2)
                if settings.get("open_folder_after") and platform.system() == "Windows":
                    try: os.startfile(settings["target_dir"])
                    except Exception: pass
                return
            else:
                c_key = keys[sel]
                print_header()
                print("\n" * 4 + YELLOW + center(f"ÚPRAVA HODNOTY: {c_key}") + RESET)
                if c_key == "viewmodel_fov":
                    print(center("(54-68, výchozí 68)"))
                elif c_key == "viewmodel_presetpos":
                    print(center("(1=Desktop, 2=Couch, 3=Classic)"))
                new_val = safe_input("\n" + center(f"Nová hodnota (nyní '{settings_vm[c_key]}'): "))
                if new_val is not None and new_val.strip() != "":
                    settings_vm[c_key] = new_val.strip()


def autoexec_generator():
    autoexec = {
        "rate": "786432",
        "cl_cmdrate": "128",
        "cl_updaterate": "128",
        "cl_interp_ratio": "1",
        "cl_interp": "0.015625",
        "engine_low_latency_sleep_after_client_tick": "1",
        "fps_max": "0",
        "fps_max_tools": "120",
        "r_drawtracers_firstperson": "0",
        "cl_forcepreload": "1",
        "snd_voipvolume": "0.5",
        "snd_musicvolume": "0",
        "snd_headphone_pan_exponent": "1.2",
        "volume": "0.5",
        "sensitivity": "1.0",
        "zoom_sensitivity_ratio": "1.0",
        "cl_crosshairalpha": "255",
        "cl_join_advertise": "2",
        "mm_dedicated_search_maxping": "50",
        "gameinstructor_enable": "0",
        "cl_autohelp": "0",
        "cl_showhelp": "0",
        "con_enable": "1",
        "cl_allow_animated_avatars": "0",
        "cl_hide_avatar_images": "0",
        "r_show_build_info": "0"
    }
    categories = {
        "Network (sub-tick, rate)": ["rate", "cl_cmdrate", "cl_updaterate", "cl_interp_ratio",
                                     "cl_interp", "engine_low_latency_sleep_after_client_tick"],
        "FPS a Grafika": ["fps_max", "fps_max_tools", "r_drawtracers_firstperson",
                          "cl_forcepreload", "r_show_build_info"],
        "Zvuk": ["snd_voipvolume", "snd_musicvolume", "snd_headphone_pan_exponent", "volume"],
        "Myš a Citlivost": ["sensitivity", "zoom_sensitivity_ratio"],
        "HUD a Crosshair": ["cl_crosshairalpha"],
        "Matchmaking": ["cl_join_advertise", "mm_dedicated_search_maxping"],
        "Utility": ["gameinstructor_enable", "cl_autohelp", "cl_showhelp", "con_enable",
                     "cl_allow_animated_avatars", "cl_hide_avatar_images"]
    }

    custom_commands = []
    sel = 0
    keys = list(autoexec.keys())

    while True:
        opts = [f"{k.ljust(48)}: {autoexec[k]}" for k in keys]
        opts.append("")
        if custom_commands:
            for i, cmd in enumerate(custom_commands):
                opts.append(f"{CYAN}[Vlastní] {cmd}{RESET}")
        opts.append(YELLOW + "+ Přidat vlastní příkaz" + RESET)
        opts.append("")
        opts.append(GREEN + "Uložit do cs2_autoexec.cfg" + RESET)

        render_menu("CS2 AUTOEXEC CONFIG GENERÁTOR", opts, sel,
                     footer="[W/S] Pohyb | [Enter] Upravit | [A/Esc] Zpět")
        k = read_key()
        if k in ['a', 'esc', 'q']: return
        elif k == 'w' and sel > 0: sel -= 1
        elif k == 's' and sel < len(opts) - 1: sel += 1
        elif k in ['d', 'enter', 'space']:
            if opts[sel] == "": continue
            if "Uložit" in opts[sel]:
                os.makedirs(settings["target_dir"], exist_ok=True)
                path = os.path.join(settings["target_dir"], "cs2_autoexec.cfg")
                with open(path, "w", encoding="utf-8") as f:
                    f.write("// CS2 Autoexec - Generated by ZeddiHub CS2 Tools\n")
                    f.write("// https://zeddihub.eu\n\n")
                    for cat_name, cat_keys in categories.items():
                        f.write(f"// === {cat_name} ===\n")
                        for ck in cat_keys:
                            f.write(f'{ck} "{autoexec[ck]}"\n')
                        f.write("\n")
                    if custom_commands:
                        f.write("// === Vlastní příkazy ===\n")
                        for cmd in custom_commands:
                            f.write(f"{cmd}\n")
                        f.write("\n")
                    f.write('echo "ZeddiHub CS2 autoexec loaded!"\nhost_writeconfig\n')
                print_header()
                print("\n" * 4 + GREEN + center("Soubor cs2_autoexec.cfg úspěšně vygenerován!") + RESET)
                time.sleep(2)
                if settings.get("open_folder_after") and platform.system() == "Windows":
                    try: os.startfile(settings["target_dir"])
                    except Exception: pass
                return
            elif "Přidat vlastní" in opts[sel]:
                print_header()
                print("\n" * 4 + YELLOW + center("PŘIDAT VLASTNÍ PŘÍKAZ") + RESET)
                print(GRAY + center("Např: bind f3 \"toggle cl_righthand 0 1\"") + RESET)
                new_cmd = safe_input("\n" + center("Příkaz: "))
                if new_cmd is not None and new_cmd.strip():
                    custom_commands.append(new_cmd.strip())
            elif "[Vlastní]" in opts[sel]:
                # Edit or remove custom command
                custom_idx = sel - len(keys) - 1
                if 0 <= custom_idx < len(custom_commands):
                    print_header()
                    print("\n" * 4 + YELLOW + center(f"ÚPRAVA: {custom_commands[custom_idx]}") + RESET)
                    print(center("[Enter] Upravit | [D] Smazat"))
                    dk = read_key(allow_esc_exit=False)
                    if dk == 'd':
                        custom_commands.pop(custom_idx)
                    elif dk in ['enter']:
                        new_cmd = safe_input("\n" + center("Nový příkaz: "))
                        if new_cmd is not None and new_cmd.strip():
                            custom_commands[custom_idx] = new_cmd.strip()
            elif sel < len(keys):
                c_key = keys[sel]
                print_header()
                print("\n" * 4 + YELLOW + center(f"ÚPRAVA HODNOTY: {c_key}") + RESET)
                new_val = safe_input("\n" + center(f"Nová hodnota (nyní '{autoexec[c_key]}'): "))
                if new_val is not None and new_val.strip() != "":
                    autoexec[c_key] = new_val.strip()


def practice_config():
    cmds = {
        "sv_cheats": "1",
        "mp_warmup_end": "",
        "bot_kick": "",
        "sv_infinite_ammo": "1",
        "mp_buy_anywhere": "1",
        "mp_buytime": "99999",
        "mp_freezetime": "0",
        "mp_roundtime_defuse": "60",
        "mp_roundtime": "60",
        "mp_maxmoney": "65535",
        "mp_startmoney": "65535",
        "sv_grenade_trajectory_prac_pipreview": "1",
        "sv_grenade_trajectory_prac_trailtime": "4",
        "cl_grenadepreview": "1",
        "mp_restartgame": "1"
    }
    sel = 0
    keys = list(cmds.keys())
    while True:
        opts = []
        for ck in keys:
            v = cmds[ck]
            display = f"{ck.ljust(42)}: {v}" if v else f"{ck} (příkaz bez hodnoty)"
            opts.append(display)
        opts.append("")
        opts.append(GREEN + "Uložit do cs2_practice.cfg" + RESET)
        render_menu("CS2 PRACTICE CONFIG GENERÁTOR", opts, sel,
                     footer="[W/S] Pohyb | [Enter] Upravit | [A/Esc] Zpět")
        k = read_key()
        if k in ['a', 'esc', 'q']: return
        elif k == 'w' and sel > 0: sel -= 1
        elif k == 's' and sel < len(opts) - 1: sel += 1
        elif k in ['d', 'enter', 'space']:
            if opts[sel] == "": continue
            if "Uložit" in opts[sel]:
                os.makedirs(settings["target_dir"], exist_ok=True)
                path = os.path.join(settings["target_dir"], "cs2_practice.cfg")
                with open(path, "w", encoding="utf-8") as f:
                    f.write("// CS2 Practice Mode - Generated by ZeddiHub CS2 Tools\n")
                    f.write("// Použijte: exec cs2_practice\n\n")
                    for kn, vv in cmds.items():
                        if vv:
                            f.write(f"{kn} {vv}\n")
                        else:
                            f.write(f"{kn}\n")
                    f.write('\necho "Practice mode activated!"\n')
                print_header()
                print("\n" * 4 + GREEN + center("Soubor cs2_practice.cfg úspěšně vygenerován!") + RESET)
                time.sleep(2)
                if settings.get("open_folder_after") and platform.system() == "Windows":
                    try: os.startfile(settings["target_dir"])
                    except Exception: pass
                return
            else:
                c_key = keys[sel]
                if not cmds[c_key]:
                    continue
                print_header()
                print("\n" * 4 + YELLOW + center(f"ÚPRAVA HODNOTY: {c_key}") + RESET)
                new_val = safe_input("\n" + center(f"Nová hodnota (nyní '{cmds[c_key]}'): "))
                if new_val is not None and new_val.strip() != "":
                    cmds[c_key] = new_val.strip()


def buy_binds_generator():
    binds = {
        "kp_ins":   ("AK-47 / M4A4", "buy ak47; buy m4a1;"),
        "kp_end":   ("AWP", "buy awp;"),
        "kp_downarrow": ("Deagle", "buy deagle;"),
        "kp_pgdn":  ("Full Armor + Defuse", "buy vesthelm; buy defuser;"),
        "kp_leftarrow": ("Smoke + Flash + Molotov", "buy smokegrenade; buy flashbang; buy molotov; buy incgrenade;"),
        "kp_5":     ("HE Grenade", "buy hegrenade;"),
        "kp_rightarrow": ("Decoy", "buy decoy;"),
        "kp_home":  ("MP9 / MAC-10", "buy mp9; buy mac10;"),
        "kp_uparrow": ("Famas / Galil", "buy famas; buy galilar;"),
        "kp_pgup":  ("Full Buy (Rifle + Armor + Nades)", "buy ak47; buy m4a1; buy vesthelm; buy defuser; buy smokegrenade; buy flashbang; buy molotov; buy hegrenade;"),
    }
    sel = 0
    bind_keys = list(binds.keys())
    while True:
        opts = []
        for bk in bind_keys:
            label, cmd = binds[bk]
            opts.append(f"[{bk.ljust(14)}] {label}")
        opts.append("")
        opts.append(GREEN + "Uložit do cs2_buybinds.cfg" + RESET)
        render_menu("CS2 BUY BINDS GENERÁTOR", opts, sel,
                     footer="[W/S] Pohyb | [Enter] Změnit příkaz | [A/Esc] Zpět")
        k = read_key()
        if k in ['a', 'esc', 'q']: return
        elif k == 'w' and sel > 0: sel -= 1
        elif k == 's' and sel < len(opts) - 1: sel += 1
        elif k in ['d', 'enter', 'space']:
            if opts[sel] == "": continue
            if "Uložit" in opts[sel]:
                os.makedirs(settings["target_dir"], exist_ok=True)
                path = os.path.join(settings["target_dir"], "cs2_buybinds.cfg")
                with open(path, "w", encoding="utf-8") as f:
                    f.write("// CS2 Buy Binds - Generated by ZeddiHub CS2 Tools\n\n")
                    for bk in bind_keys:
                        label, cmd = binds[bk]
                        f.write(f'bind "{bk}" "{cmd}" // {label}\n')
                    f.write('\necho "ZeddiHub buy binds loaded!"\n')
                print_header()
                print("\n" * 4 + GREEN + center("Soubor cs2_buybinds.cfg úspěšně vygenerován!") + RESET)
                time.sleep(2)
                if settings.get("open_folder_after") and platform.system() == "Windows":
                    try: os.startfile(settings["target_dir"])
                    except Exception: pass
                return
            else:
                bk = bind_keys[sel]
                label, cmd = binds[bk]
                print_header()
                print("\n" * 4 + YELLOW + center(f"ÚPRAVA BINDU: {bk} ({label})") + RESET)
                print(CYAN + center(f"Aktuální příkaz: {cmd}") + RESET)
                new_cmd = safe_input("\n" + center("Nový příkaz (nebo ESC pro zrušení): "))
                if new_cmd is not None and new_cmd.strip():
                    binds[bk] = (label, new_cmd.strip())
