import os
import re
import time
import shutil
import json
import platform
import socket
import tkinter as tk
from tkinter import filedialog
from .core import *


def server_cfg_generator():
    cfg = {
        "hostname": "ZeddiHub CS2 Server",
        "sv_password": "",
        "rcon_password": "changeme",
        "sv_cheats": "0",
        "sv_lan": "0",
        "game_mode": "1",
        "game_type": "0",
        "sv_maxrate": "0",
        "sv_minrate": "128000",
        "sv_maxcmdrate": "128",
        "sv_mincmdrate": "64",
        "sv_maxupdaterate": "128",
        "sv_minupdaterate": "64",
        "mp_autoteambalance": "1",
        "mp_limitteams": "1",
        "mp_friendlyfire": "0",
        "mp_roundtime": "1.92",
        "mp_freezetime": "15",
        "mp_buytime": "20",
        "mp_maxrounds": "24",
        "sv_alltalk": "0",
        "sv_deadtalk": "1",
        "sv_allow_votes": "1",
        "tv_enable": "1",
        "tv_delay": "30",
        "exec_after_warm": ""
    }
    categories = {
        "Základní": ["hostname", "sv_password", "rcon_password", "sv_cheats", "sv_lan"],
        "Gamemode": ["game_mode", "game_type"],
        "Network": ["sv_maxrate", "sv_minrate", "sv_maxcmdrate", "sv_mincmdrate", "sv_maxupdaterate", "sv_minupdaterate"],
        "Gameplay": ["mp_autoteambalance", "mp_limitteams", "mp_friendlyfire", "mp_roundtime", "mp_freezetime", "mp_buytime", "mp_maxrounds"],
        "Komunikace": ["sv_alltalk", "sv_deadtalk", "sv_allow_votes"],
        "GOTV": ["tv_enable", "tv_delay"]
    }

    sel = 0
    keys = list(cfg.keys())
    while True:
        opts = [f"{k.ljust(28)}: {cfg[k] if cfg[k] else '(prázdné)'}" for k in keys]
        opts.append("")
        opts.append(GREEN + "Uložit do server.cfg" + RESET)
        render_menu("CS2 SERVER.CFG GENERÁTOR", opts, sel,
                     footer="[W/S] Pohyb | [Enter] Upravit | [A/Esc] Zpět")
        k = read_key()
        if k in ['a', 'esc', 'q']: return
        elif k == 'w' and sel > 0: sel -= 1
        elif k == 's' and sel < len(opts) - 1: sel += 1
        elif k in ['d', 'enter', 'space']:
            if opts[sel] == "": continue
            if "Uložit" in opts[sel]:
                os.makedirs(settings["target_dir"], exist_ok=True)
                path = os.path.join(settings["target_dir"], "server.cfg")
                with open(path, "w", encoding="utf-8") as f:
                    f.write("// CS2 Server Config - Generated by ZeddiHub CS2 Tools\n")
                    f.write("// https://zeddihub.eu\n\n")
                    for cat_name, cat_keys in categories.items():
                        f.write(f"// === {cat_name} ===\n")
                        for ck in cat_keys:
                            if cfg[ck]:
                                if ck in ["hostname", "sv_password", "rcon_password"]:
                                    f.write(f'{ck} "{cfg[ck]}"\n')
                                else:
                                    f.write(f"{ck} {cfg[ck]}\n")
                        f.write("\n")
                    f.write('echo "[ZeddiHub] Server config loaded!"\n')
                print_header()
                print("\n" * 4 + GREEN + center("Soubor server.cfg úspěšně vygenerován!") + RESET)
                time.sleep(2)
                if settings.get("open_folder_after") and platform.system() == "Windows":
                    try: os.startfile(settings["target_dir"])
                    except Exception: pass
                return
            else:
                c_key = keys[sel]
                print_header()
                print("\n" * 4 + YELLOW + center(f"ÚPRAVA: {c_key}") + RESET)
                if c_key == "game_mode":
                    print(center("(0=Casual, 1=Competitive, 2=Wingman, 3=Deathmatch)"))
                elif c_key == "game_type":
                    print(center("(0=Classic, 1=Gun Game, 2=Training, 3=Custom)"))
                new_val = safe_input("\n" + center(f"Nová hodnota (nyní '{cfg[c_key]}'): "))
                if new_val is not None:
                    cfg[c_key] = new_val.strip()


def gamemode_config():
    modes = {
        "Competitive 5v5": {"game_mode": "1", "game_type": "0", "mp_maxrounds": "24", "mp_roundtime": "1.92",
                            "mp_freezetime": "15", "mp_buytime": "20", "mp_startmoney": "800"},
        "Competitive MR12": {"game_mode": "1", "game_type": "0", "mp_maxrounds": "24", "mp_roundtime": "1.92",
                             "mp_freezetime": "15", "mp_buytime": "20", "mp_startmoney": "800",
                             "mp_overtime_enable": "1", "mp_overtime_maxrounds": "6"},
        "Wingman 2v2": {"game_mode": "2", "game_type": "0", "mp_maxrounds": "16", "mp_roundtime": "1.5",
                        "mp_freezetime": "10", "mp_buytime": "15", "mp_startmoney": "800",
                        "mp_teammates_are_enemies": "0"},
        "Deathmatch": {"game_mode": "2", "game_type": "1", "mp_roundtime": "10", "mp_freezetime": "0",
                       "mp_buytime": "0", "mp_startmoney": "65535", "sv_infinite_ammo": "2",
                       "mp_respawn_on_death_ct": "1", "mp_respawn_on_death_t": "1"},
        "Casual": {"game_mode": "0", "game_type": "0", "mp_maxrounds": "15", "mp_roundtime": "2.25",
                   "mp_freezetime": "10", "mp_buytime": "30", "mp_startmoney": "1000"},
        "Retake": {"game_mode": "0", "game_type": "0", "mp_maxrounds": "8", "mp_roundtime": "0.92",
                   "mp_freezetime": "3", "mp_buytime": "0", "mp_startmoney": "0",
                   "sv_enablebunnyhopping": "1"},
    }
    sel = 0
    mode_keys = list(modes.keys())
    while True:
        render_menu("CS2 GAMEMODE PRESETY", mode_keys, sel,
                     [f"Příkazů: {len(modes[m])}" for m in mode_keys],
                     footer="[W/S] Pohyb | [Enter] Vygenerovat | [A/Esc] Zpět")
        k = read_key()
        if k in ['a', 'esc', 'q']: return
        elif k == 'w' and sel > 0: sel -= 1
        elif k == 's' and sel < len(mode_keys) - 1: sel += 1
        elif k in ['d', 'enter', 'space']:
            chosen = mode_keys[sel]
            data = modes[chosen]
            os.makedirs(settings["target_dir"], exist_ok=True)
            safe_name = chosen.lower().replace(" ", "_").replace("/", "")
            path = os.path.join(settings["target_dir"], f"cs2_gamemode_{safe_name}.cfg")
            with open(path, "w", encoding="utf-8") as f:
                f.write(f"// CS2 Gamemode: {chosen}\n// Generated by ZeddiHub CS2 Tools\n\n")
                for ck, cv in data.items():
                    f.write(f"{ck} {cv}\n")
                f.write(f'\necho "[ZeddiHub] Gamemode {chosen} loaded!"\n')
            print_header()
            print("\n" * 4 + GREEN + center(f"Gamemode '{chosen}' úspěšně vygenerován!") + RESET)
            time.sleep(2)
            if settings.get("open_folder_after") and platform.system() == "Windows":
                try: os.startfile(settings["target_dir"])
                except Exception: pass
            return


def map_group_editor():
    map_pools = {
        "Active Duty": ["de_dust2", "de_mirage", "de_inferno", "de_nuke", "de_overpass",
                        "de_ancient", "de_anubis", "de_vertigo"],
        "Wingman": ["de_inferno", "de_overpass", "de_vertigo", "de_nuke", "de_shortdust"],
        "Deathmatch": ["de_dust2", "de_mirage", "de_inferno", "de_nuke", "de_overpass",
                       "de_ancient", "de_anubis", "cs_office"],
        "Custom": []
    }
    sel = 0
    pool_keys = list(map_pools.keys())
    while True:
        opts = [f"{name} ({len(maps)} map)" for name, maps in zip(pool_keys, [map_pools[k] for k in pool_keys])]
        opts.append("")
        opts.append(CYAN + "Přidat vlastní mapu do Custom poolu" + RESET)
        render_menu("CS2 MAP GROUP EDITOR", opts, sel,
                     footer="[W/S] Pohyb | [Enter] Vygenerovat/Upravit | [A/Esc] Zpět")
        k = read_key()
        if k in ['a', 'esc', 'q']: return
        elif k == 'w' and sel > 0: sel -= 1
        elif k == 's' and sel < len(opts) - 1: sel += 1
        elif k in ['d', 'enter', 'space']:
            if opts[sel] == "": continue
            if "Přidat" in opts[sel]:
                print_header()
                print("\n" * 4 + YELLOW + center("NOVÁ MAPA DO CUSTOM POOLU") + RESET)
                new_map = safe_input("\n" + center("Název mapy (např. de_dust2 nebo workshop/id): "))
                if new_map and new_map.strip():
                    map_pools["Custom"].append(new_map.strip())
                    print_header()
                    print("\n" * 4 + GREEN + center(f"Mapa '{new_map.strip()}' přidána!") + RESET)
                    time.sleep(1)
            elif sel < len(pool_keys):
                chosen = pool_keys[sel]
                maps = map_pools[chosen]
                if not maps:
                    print_header()
                    print("\n" * 4 + RED + center("Tento pool je prázdný! Přidejte mapy nejdříve.") + RESET)
                    time.sleep(2)
                    continue
                os.makedirs(settings["target_dir"], exist_ok=True)
                safe_name = chosen.lower().replace(" ", "_")
                path = os.path.join(settings["target_dir"], f"cs2_mapgroup_{safe_name}.txt")
                with open(path, "w", encoding="utf-8") as f:
                    f.write(f"// CS2 Map Group: {chosen}\n// Generated by ZeddiHub CS2 Tools\n\n")
                    f.write(f'"cs2_mapgroup_{safe_name}"\n')
                    f.write("{\n")
                    for m in maps:
                        f.write(f'\t"{m}"\t""\n')
                    f.write("}\n")
                print_header()
                print("\n" * 4 + GREEN + center(f"Map group '{chosen}' úspěšně vygenerován!") + RESET)
                time.sleep(2)
                if settings.get("open_folder_after") and platform.system() == "Windows":
                    try: os.startfile(settings["target_dir"])
                    except Exception: pass


def rcon_client():
    host = "127.0.0.1"
    port = 27015
    password = ""

    print_header()
    print("\n" * 3 + YELLOW + BOLD + center("CS2 RCON KLIENT") + RESET)
    print(GRAY + center("Připojte se k CS2 serveru a posílejte příkazy vzdáleně.") + RESET)

    h = safe_input("\n" + center("IP adresa serveru (výchozí 127.0.0.1): "))
    if h and h.strip(): host = h.strip()

    p = safe_input(center("Port (výchozí 27015): "))
    if p and p.strip():
        try: port = int(p.strip())
        except: pass

    pw = safe_input(center("RCON heslo: "))
    if pw is None: return
    password = pw.strip()
    if not password:
        print_header()
        print("\n" * 4 + RED + center("RCON heslo nesmí být prázdné!") + RESET)
        time.sleep(2)
        return

    def build_rcon_packet(req_id, ptype, body):
        body_encoded = body.encode('utf-8') + b'\x00\x00'
        size = 4 + 4 + len(body_encoded)
        import struct
        return struct.pack('<iii', size, req_id, ptype) + body_encoded

    def read_rcon_response(sock):
        import struct
        data = sock.recv(4)
        if len(data) < 4: return None, None
        size = struct.unpack('<i', data)[0]
        rest = b''
        while len(rest) < size:
            chunk = sock.recv(size - len(rest))
            if not chunk: break
            rest += chunk
        if len(rest) < 8: return None, None
        req_id, resp_type = struct.unpack('<ii', rest[:8])
        body = rest[8:].rstrip(b'\x00')
        return req_id, body.decode('utf-8', errors='replace')

    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(5)
        sock.connect((host, port))

        auth_pkt = build_rcon_packet(1, 3, password)
        sock.sendall(auth_pkt)
        req_id, body = read_rcon_response(sock)
        req_id2, body2 = read_rcon_response(sock)

        if req_id2 == -1:
            print_header()
            print("\n" * 4 + RED + center("Autentizace selhala! Špatné RCON heslo.") + RESET)
            time.sleep(3)
            sock.close()
            return

        print_header()
        print("\n" + GREEN + center(f"Připojeno k {host}:{port}") + RESET)
        print(GRAY + center("Zadejte příkazy. Napsáním 'exit' se odpojíte.") + RESET)
        print(GRAY + center("-" * 60) + RESET + "\n")

        while True:
            cmd = safe_input(f"{CYAN}rcon>{RESET} ")
            if cmd is None or cmd.strip().lower() == "exit":
                break
            if not cmd.strip():
                continue
            cmd_pkt = build_rcon_packet(2, 2, cmd.strip())
            sock.sendall(cmd_pkt)
            time.sleep(0.3)
            req_id, response = read_rcon_response(sock)
            if response:
                for line in response.splitlines():
                    print(f"  {WHITE}{line}{RESET}")
            else:
                print(f"  {GRAY}(žádná odpověď){RESET}")

        sock.close()
        print_header()
        print("\n" * 4 + GREEN + center("RCON relace ukončena.") + RESET)
        time.sleep(1.5)

    except socket.timeout:
        print_header()
        print("\n" * 4 + RED + center(f"Časový limit připojení k {host}:{port} vypršel!") + RESET)
        time.sleep(3)
    except ConnectionRefusedError:
        print_header()
        print("\n" * 4 + RED + center(f"Server {host}:{port} odmítl připojení!") + RESET)
        time.sleep(3)
    except Exception as e:
        print_header()
        print("\n" * 4 + RED + center(f"Chyba RCON: {e}") + RESET)
        time.sleep(3)
