<script lang="ts">
  /**
   * CS:GO Autoexec — single "Herní nastavení" section, 14 fields.
   * Mirrors legacy/gui/panels/csgo.py:_build_autoexec.
   */

  import { Save } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Section from "$components/form/Section.svelte";
  import EntryRow from "$components/form/EntryRow.svelte";
  import { saveCfgFile } from "$api/saveFile";

  const FIELDS: [string, string, string][] = [
    ["rate", "Rate", "786432"],
    ["cl_cmdrate", "Cmdrate", "128"],
    ["cl_updaterate", "Updaterate", "128"],
    ["cl_interp_ratio", "Interp ratio", "1"],
    ["cl_interp", "Interp", "0.015625"],
    ["fps_max", "FPS max", "300"],
    ["sensitivity", "Citlivost", "1.0"],
    ["zoom_sensitivity_ratio_mouse", "Zoom cit.", "1.0"],
    ["con_enable", "Konzole", "1"],
    ["snd_musicvolume", "Hudba", "0"],
    ["volume", "Hlasitost", "0.5"],
    ["gameinstructor_enable", "Instructor", "0"],
    ["cl_autohelp", "Auto help", "0"],
    ["mm_dedicated_search_maxping", "Max ping", "50"],
  ];

  let values = $state<Record<string, string>>({});
  for (const [k, _l, def] of FIELDS) values[k] = def;
  let custom = $state("// Vlastní příkazy\n");
  let saveStatus = $state("");

  async function saveCfg() {
    saveStatus = "";
    let content = "// CS:GO Autoexec - Generated by ZeddiHub Tools\n\n";
    for (const [k] of FIELDS) content += `${k} "${values[k]}"\n`;
    const trimmed = custom.trim();
    if (trimmed && !trimmed.startsWith("//")) {
      content += `\n${trimmed}\n`;
    }
    content += '\necho "ZeddiHub autoexec loaded!"\n';

    try {
      const path = await saveCfgFile(content, {
        defaultName: "csgo_autoexec.cfg",
        title: "Uložit autoexec.cfg",
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">CS:GO — Autoexec Config</h3>
  <p class="text-xs text-zh-text-muted mb-3">14 polí v jedné sekci.</p>

  <Section title="Herní nastavení">
    {#each FIELDS as [k, label, _def]}
      <EntryRow label={label} bind:value={values[k]} hint={k} />
    {/each}
  </Section>

  <Section title="Vlastní příkazy">
    <textarea
      bind:value={custom}
      rows="6"
      spellcheck="false"
      class="w-full bg-zh-card-hover border border-zh-border rounded-entry px-3 py-2 text-xs font-mono leading-relaxed focus:outline-none focus:border-zh-primary resize-y"
    ></textarea>
  </Section>

  <Button variant="primary" onclick={saveCfg} class="w-full mt-3">
    <Save size={14} />
    Uložit autoexec.cfg
  </Button>

  {#if saveStatus}<div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>{/if}
</div>
