<script lang="ts">
  import { Save } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Card from "$components/ui/Card.svelte";
  import { saveCfgFile } from "$api/saveFile";

  // Same default binds as CS2
  const BINDS: [string, string, string][] = [
    ["kp_ins",        "AK-47 / M4A4",                "buy ak47; buy m4a1;"],
    ["kp_end",        "AWP",                         "buy awp;"],
    ["kp_downarrow",  "Deagle",                      "buy deagle;"],
    ["kp_pgdn",       "Armor + Defuse",              "buy vesthelm; buy defuser;"],
    ["kp_leftarrow",  "Smoke + Flash + Molotov",     "buy smokegrenade; buy flashbang; buy molotov; buy incgrenade;"],
    ["kp_5",          "HE Grenade",                  "buy hegrenade;"],
    ["kp_rightarrow", "Decoy",                       "buy decoy;"],
    ["kp_home",       "MP9 / MAC-10",                "buy mp9; buy mac10;"],
    ["kp_uparrow",    "Famas / Galil",               "buy famas; buy galilar;"],
    ["kp_pgup",       "Full Buy",                    "buy ak47; buy m4a1; buy vesthelm; buy defuser; buy smokegrenade; buy flashbang; buy molotov; buy hegrenade;"],
  ];

  let values = $state<Record<string, string>>({});
  for (const [k, _l, def] of BINDS) values[k] = def;
  let saveStatus = $state("");

  async function saveCfg() {
    saveStatus = "";
    let content = "// CS:GO Buy Binds - Generated by ZeddiHub Tools\n\n";
    for (const [k] of BINDS) content += `bind "${k}" "${values[k]}"\n`;
    content += '\necho "ZeddiHub buy binds loaded!"\n';

    try {
      const path = await saveCfgFile(content, {
        defaultName: "csgo_buybinds.cfg",
        title: "Uložit buybinds.cfg",
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">CS:GO — Buy Binds Generátor</h3>
  <p class="text-xs text-zh-text-muted mb-3">Klávesy numerické klávesnice na nákup setupů.</p>

  <Card>
    <h3 class="text-sm font-bold text-zh-primary mb-2">Klávesy a příkazy</h3>
    {#each BINDS as [key, label, _def]}
      <label class="grid grid-cols-[160px_1fr] items-center gap-3 py-1.5 text-xs">
        <div class="font-mono text-zh-text-muted">
          [{key}]
          <span class="text-zh-text block leading-tight font-sans">{label}</span>
        </div>
        <input type="text" bind:value={values[key]}
          class="bg-zh-card-hover border border-zh-border rounded-entry px-3 h-8 text-[11px] font-mono focus:outline-none focus:border-zh-primary" />
      </label>
    {/each}
  </Card>

  <Button variant="primary" onclick={saveCfg} class="w-full mt-3">
    <Save size={14} />
    Uložit buybinds.cfg
  </Button>

  {#if saveStatus}<div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>{/if}
</div>
