<script lang="ts">
  import { Save } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Section from "$components/form/Section.svelte";
  import EntryRow from "$components/form/EntryRow.svelte";
  import { saveCfgFile } from "$api/saveFile";

  // Mirror legacy csgo.py:_build_practice (11 fields)
  const FIELDS: [string, string, string][] = [
    ["sv_cheats", "SV Cheats", "1"],
    ["sv_infinite_ammo", "Nekonečná munice", "1"],
    ["mp_buy_anywhere", "Kupovat kdekoliv", "1"],
    ["mp_buytime", "Buy time", "99999"],
    ["mp_freezetime", "Freeze time", "0"],
    ["mp_roundtime", "Round time", "60"],
    ["mp_maxmoney", "Max peníze", "65535"],
    ["mp_startmoney", "Start peníze", "65535"],
    ["sv_grenade_trajectory_prac_pipreview", "Nade preview", "1"],
    ["sv_grenade_trajectory_prac_trailtime", "Nade trail", "4"],
    ["cl_grenadepreview", "Grenade preview", "1"],
  ];

  let values = $state<Record<string, string>>({});
  for (const [k, _l, def] of FIELDS) values[k] = def;
  let saveStatus = $state("");

  async function saveCfg() {
    saveStatus = "";
    let content = "// CS:GO Practice - Generated by ZeddiHub Tools\n";
    content += "// exec csgo_practice\n\n";
    content += "mp_warmup_end\nbot_kick\n\n";
    for (const [k] of FIELDS) content += `${k} ${values[k]}\n`;
    content += "\nmp_restartgame 1\necho \"Practice mode activated!\"\n";

    try {
      const path = await saveCfgFile(content, {
        defaultName: "csgo_practice.cfg",
        title: "Uložit practice.cfg",
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">CS:GO — Practice Config</h3>
  <p class="text-xs text-zh-text-muted mb-3">Trénink granátů, nekonečná munice…</p>

  <Section title="Nastavení">
    {#each FIELDS as [k, label, _def]}
      <EntryRow label={label} bind:value={values[k]} hint={k} />
    {/each}
  </Section>

  <Button variant="primary" onclick={saveCfg} class="w-full mt-3">
    <Save size={14} />
    Uložit practice.cfg
  </Button>

  {#if saveStatus}<div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>{/if}
</div>
