<script lang="ts">
  /**
   * CS:GO Server.cfg generator — slightly smaller cvar set than CS2,
   * mp_maxrounds default = 30 (vs 24), single sv_maxrate field.
   * Mirrors legacy/gui/panels/csgo.py:_build_servercfg.
   */

  import { Save } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Section from "$components/form/Section.svelte";
  import EntryRow from "$components/form/EntryRow.svelte";
  import Stepper from "$components/form/Stepper.svelte";
  import Dropdown from "$components/form/Dropdown.svelte";
  import BoolToggle from "$components/form/BoolToggle.svelte";
  import { saveCfgFile } from "$api/saveFile";

  const QUOTED = new Set(["hostname", "sv_password", "rcon_password"]);

  // Základní
  let hostname        = $state("ZeddiHub CS:GO Server");
  let sv_password     = $state("");
  let rcon_password   = $state("changeme");
  let sv_cheats       = $state("0");
  let sv_lan          = $state("0");
  // Gamemode
  let game_type       = $state("0");
  let game_mode       = $state("1");
  // Network
  let sv_maxrate      = $state("786432");
  // Gameplay
  let mp_autoteambalance = $state("1");
  let mp_limitteams      = $state("1");
  let mp_friendlyfire    = $state("0");
  let mp_maxrounds       = $state("30");
  let mp_roundtime       = $state("1.92");
  let mp_freezetime      = $state("15");
  let mp_buytime         = $state("20");
  // Komunikace
  let sv_alltalk       = $state("0");
  let sv_deadtalk      = $state("1");
  // GOTV
  let tv_enable        = $state("1");
  let tv_delay         = $state("30");

  let saveStatus = $state("");

  function buildVars() {
    return {
      hostname, sv_password, rcon_password, sv_cheats, sv_lan,
      game_type, game_mode, sv_maxrate,
      mp_autoteambalance, mp_limitteams, mp_friendlyfire, mp_maxrounds, mp_roundtime, mp_freezetime, mp_buytime,
      sv_alltalk, sv_deadtalk,
      tv_enable, tv_delay,
    };
  }

  async function saveCfg() {
    saveStatus = "";
    let content = "// CS:GO Server Config - Generated by ZeddiHub Tools\n\n";
    for (const [k, v] of Object.entries(buildVars())) {
      if (!v) continue;
      if (QUOTED.has(k)) content += `${k} "${v}"\n`;
      else                content += `${k} ${v}\n`;
    }
    content += '\necho "[ZeddiHub] Server config loaded!"\n';
    try {
      const path = await saveCfgFile(content, {
        defaultName: "server.cfg",
        title: "Uložit server.cfg",
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">CS:GO — Server.cfg Generátor</h3>
  <p class="text-xs text-zh-text-muted mb-3">Vygeneruje server.cfg podle vyplněných hodnot.</p>

  <Section title="Základní">
    <EntryRow label="Název serveru" bind:value={hostname} />
    <EntryRow label="Heslo serveru" bind:value={sv_password}   type="password" hint="prázdné = bez hesla" />
    <EntryRow label="RCON heslo"     bind:value={rcon_password} type="password" />
    <BoolToggle label="SV Cheats" bind:value={sv_cheats} />
    <BoolToggle label="LAN only"  bind:value={sv_lan} />
  </Section>

  <Section title="Gamemode">
    <Dropdown label="Game type" bind:value={game_type}
      options={[
        { value: "0", label: "0 — Classic" },
        { value: "1", label: "1 — GunGame" },
        { value: "2", label: "2 — Training" },
      ]}
    />
    <Dropdown label="Game mode" bind:value={game_mode}
      options={[
        { value: "0", label: "0 — Casual" },
        { value: "1", label: "1 — Competitive" },
        { value: "2", label: "2 — Wingman" },
      ]}
    />
  </Section>

  <Section title="Network">
    <Stepper label="Max rate" bind:value={sv_maxrate} min={0} max={786_432} step={128_000} />
  </Section>

  <Section title="Gameplay">
    <BoolToggle label="Auto balance"      bind:value={mp_autoteambalance} />
    <BoolToggle label="Limit teams"       bind:value={mp_limitteams} />
    <BoolToggle label="Friendly fire"     bind:value={mp_friendlyfire} />
    <Dropdown   label="Max rounds"        bind:value={mp_maxrounds} options={["12", "16", "24", "30"]} />
    <Stepper    label="Round time (min)"  bind:value={mp_roundtime}  min={0.5} max={10} step={0.5} />
    <Stepper    label="Freeze time (s)"   bind:value={mp_freezetime} min={0}   max={30} step={1} />
    <Stepper    label="Buy time (s)"      bind:value={mp_buytime}    min={0}   max={90} step={5} />
  </Section>

  <Section title="Komunikace">
    <BoolToggle label="All talk"  bind:value={sv_alltalk} />
    <BoolToggle label="Dead talk" bind:value={sv_deadtalk} />
  </Section>

  <Section title="GOTV">
    <BoolToggle label="GOTV enable"    bind:value={tv_enable} />
    <Stepper    label="GOTV delay (s)" bind:value={tv_delay} min={0} max={120} step={10} />
  </Section>

  <Button variant="primary" onclick={saveCfg} class="w-full mt-3">
    <Save size={14} />
    Uložit server.cfg
  </Button>

  {#if saveStatus}<div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>{/if}
</div>
