<script lang="ts">
  /**
   * CS:GO Viewmodel Tab — same cvars as CS2, but defaults differ:
   * FOV 60 (CS:GO) vs 68 (CS2), bob_lat 0.33 vs 0.1, bob_vert 0.14 vs 0.1.
   */

  import { Save } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Card from "$components/ui/Card.svelte";
  import Stepper from "$components/form/Stepper.svelte";
  import Dropdown from "$components/form/Dropdown.svelte";
  import { saveCfgFile } from "$api/saveFile";

  let viewmodel_fov       = $state("60");
  let viewmodel_offset_x  = $state("2.5");
  let viewmodel_offset_y  = $state("0");
  let viewmodel_offset_z  = $state("-1.5");
  let viewmodel_presetpos = $state("3");
  let cl_bob_lower_amt    = $state("5");
  let cl_bobamt_lat       = $state("0.33");
  let cl_bobamt_vert      = $state("0.14");

  let saveStatus = $state("");

  async function saveCfg() {
    saveStatus = "";
    const vars = {
      viewmodel_fov, viewmodel_offset_x, viewmodel_offset_y, viewmodel_offset_z,
      viewmodel_presetpos, cl_bob_lower_amt, cl_bobamt_lat, cl_bobamt_vert,
    };
    let content = "// CS:GO Viewmodel - Generated by ZeddiHub Tools\n\n";
    for (const [k, v] of Object.entries(vars)) content += `${k} "${v}"\n`;
    try {
      const path = await saveCfgFile(content, {
        defaultName: "csgo_viewmodel.cfg",
        title: "Uložit viewmodel.cfg",
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">CS:GO — Viewmodel Generátor</h3>
  <p class="text-xs text-zh-text-muted mb-3">Pozice zbraně a bob — CS:GO defaulty.</p>

  <Card>
    <Stepper bind:value={viewmodel_fov}       label="FOV"      min={54}   max={68}  step={1}   hint="54–68" />
    <Stepper bind:value={viewmodel_offset_x}  label="Offset X" min={-2.5} max={2.5} step={0.5} hint="−2.5 – +2.5" />
    <Stepper bind:value={viewmodel_offset_y}  label="Offset Y" min={-2.5} max={2.5} step={0.5} hint="−2.5 – +2.5" />
    <Stepper bind:value={viewmodel_offset_z}  label="Offset Z" min={-2.5} max={2.5} step={0.5} hint="−2.5 – +2.5" />
    <Dropdown bind:value={viewmodel_presetpos} label="Preset"
      options={[
        { value: "1", label: "1 — Desktop" },
        { value: "2", label: "2 — Couch" },
        { value: "3", label: "3 — Classic" },
      ]}
    />
    <Stepper bind:value={cl_bob_lower_amt} label="Bob Lower" min={5}   max={30}  step={1}   hint="5–30" />
    <Stepper bind:value={cl_bobamt_lat}    label="Bob Lat"   min={0}   max={2}   step={0.01} hint="0–2" />
    <Stepper bind:value={cl_bobamt_vert}   label="Bob Vert"  min={0}   max={2}   step={0.01} hint="0–2" />
  </Card>

  <Button variant="primary" onclick={saveCfg} class="w-full mt-3">
    <Save size={14} />
    Uložit viewmodel.cfg
  </Button>

  {#if saveStatus}<div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>{/if}
</div>
