SUPPORTED_LANGS = {
    "en": "English (en)", "cs": "Czech (cs)", "de": "German (de)", "ru": "Russian (ru)",
    "es": "Spanish (es)", "fr": "French (fr)", "it": "Italian (it)", "nl": "Dutch (nl)",
    "pl": "Polish (pl)", "pt": "Portuguese (pt)", "tr": "Turkish (tr)", "zh": "Chinese (zh)",
    "ja": "Japanese (ja)", "ko": "Korean (ko)", "uk": "Ukrainian (uk)", "ro": "Romanian (ro)",
    "da": "Danish (da)", "fi": "Finnish (fi)", "hu": "Hungarian (hu)", "no": "Norwegian (no)",
    "sv": "Swedish (sv)", "ar": "Arabic (ar)", "bg": "Bulgarian (bg)", "el": "Greek (el)",
    "hi": "Hindi (hi)", "id": "Indonesian (id)", "th": "Thai (th)", "vi": "Vietnamese (vi)"
}

L = {
    "cz": {
        "welcome": "Vítej v ZeddiHub Translator", "quote": "Každý je dobrý, ale s námi nejlepší!",
        "main_menu": "HLAVNÍ MENU", "m_run": "Spustit Hromadný Překlad", "m_sel": "Selektivní Překládání",
        "m_prefix": "Prefix Manager", "m_settings": "Nastavení", "m_folders": "Přehled složek", 
        "m_cleanup": "Vyčistit složky", "m_credits": "Credits a Odkazy", "m_exit": "Ukončit", 
        "d_run": "Spustí hromadný překlad všech souborů.", "d_sel": "Vyhledá frázi a umožní vlastní/automatický překlad.",
        "d_prefix": "Nastavení prefixu (barvy, text, závorky).", "d_settings": "Cesty, formáty, API, jazyk, akce po dokončení.",
        "d_folders": "Prohlížení vygenerovaných jazykových složek.", "d_cleanup": "Smaže cílové složky.",
        "d_credits": "Web, Discord, Banlist, Verze.", "d_src": "Složka s originálními texty.", "d_tgt": "Složka pro uložení překladů.",
        "d_langs": "Výběr jazyků pro překlad.", "d_fmt": "Změna koncovky souborů (.json, .txt...).",
        "d_api": "Výběr enginu (Doporučený, Google, DeepL) a vložení API.", "d_sys": "Logy, Zálohy, Rychlost, Po dokončení.",
        "d_ui": "Jazyk celé aplikace (CZ/EN).", "d_reset": "Vymaže config a provede tvrdý reset programu.",
        "footer": "[W/S] Pohyb | [D] Vybrat | [A] Zpět | [Q] Menu", "yes": "ANO", "no": "NE", 
        "confirm": "SOUHRN PŘED SPUŠTĚNÍM", "done": "ÚKOL ÚSPĚŠNĚ DOKONČEN!",
        "clean_empty": "Není co čistit. Cílové složky neexistují nebo jsou prázdné.",
        "no_folders": "Složky zatím neexistují.", "abort": "PŘEKLAD BYL ZRUŠEN UŽIVATELEM.",
        "wiz_title": "PRVOTNÍ INSTALACE ZEDDIHUB TRANSLATOR", "wiz_step1": "KROK 1: JAZYK APLIKACE",
        "wiz_step2": "KROK 2: ZDROJOVÁ SLOŽKA", "wiz_step2b": "KROK 3: JAZYK ZDROJE",
        "wiz_step3": "KROK 4: CÍLOVÁ SLOŽKA", "wiz_step4": "KROK 5: VÝBĚR PŘEKLADAČE",
        "wiz_step5": "KROK 6: FORMÁT SOUBORŮ", "wiz_step6": "KROK 7: LOGY A ZÁLOHY",
        "use_def": "Použít výchozí složku v zeddihub_translator", "retry": "Zkusit vybrat znovu",
        "err_title": "OSUDOVÁ CHYBA PROGRAMU", "err_m": "Návrat do Hlavního menu", "err_e": "Ukončit aplikaci", "err_r": "Tovární reset (Vymazat config a restartovat)",
        "pause_title": "PŘEKLAD POZASTAVEN", "resume": "Pokračovat v překladu", "m_exit_menu": "Zrušit a vrátit se do Menu",
        "o_speed": "Rychlost vizualizace", "reset_def": "Obnovit výchozí nastavení", "restarting": "RESTARTUJI APLIKACI...",
        "exit_q_title": "OPRAVDU CHCETE UKONČIT APLIKACI?", "clean_q_title": "OPRAVDU CHCETE SMAZAT TYTO SLOŽKY?",
        "v_close": "[A/Esc/Q] Zavřít prohlížeč | [T] Přeložit tuto frázi", "inp_esc": "(Můžete vložit text pomocí Ctrl+V nebo zrušit pomocí ESC)",
        "sel_src_q": "ZDROJOVÁ SLOŽKA PRO VYHLEDÁVÁNÍ", "sel_src_def": "Použít aktuální složku v Nastavení", "sel_src_new": "Vybrat jinou složku",
        "search_phrase": "Zadejte hledanou frázi (ignoruje barvy a tagy):", "search_res": "VÝSLEDKY HLEDÁNÍ (Vyberte shodu)",
        "found_keys": "NALEZENÉ KLÍČE V", "choose_act": "ZVOLTE AKCI PŘEKLADU",
        "act1": "Hromadný Auto-překlad (Všechny jazyky)", "act2": "Auto-překlad (Jen 1 zvolený jazyk)",
        "act3": "Hromadný Vlastní překlad (Všechny jazyky)", "act4": "Vlastní překlad (Jen 1 zvolený jazyk)",
        "orig_t": "PŮVODNÍ TEXT / ORIGINÁL", "new_t": "Nový text:", "sel_lang": "VYBERTE CÍLOVÝ JAZYK PRO TUTO AKCI",
        "auto_res": "NÁHLED PŘEKLADU", "save_cont": "Ukládám a pokračuji...",
        "conn_lost": "Ztráta připojení nebo Rate Limit API! Čekám 5s a zkusím to znovu...",
        "pm_d1": "Aktivuje přidávání prefixu.", "pm_d2": "Text vložený před zprávu.", "pm_d3": "Klikni pro zadání HEX nebo palety.", "pm_d4": "Závorky a detekce.",
        "pm_a1": "Uzavře prefix do [ ].", "pm_a2": "Použije stejnou barvu jako má text prefixu.", "pm_a3": "Barva pro závorky (HEX/Paleta).", "pm_a4": "Smaže cizí prefixy ze souborů.",
        "post_action": "Po dokončení", "pa_none": "Nic", "pa_exit": "Ukončit aplikaci", "pa_sleep": "Režim spánku", "pa_shutdown": "Vypnout PC",
        "empty_file": "Prázdný soubor", "detail": "DETAIL KLÍČE", "folder_q": "VYBERTE CÍLOVOU SLOŽKU PRO TENTO PŘEKLAD",
        "f_config": "Použít cílovou složku z Nastavení", "f_new": "Vybrat jinou cílovou složku", "no_phrase": "Fráze nenalezena v žádném souboru.",
        "no_files": "Žádné soubory nenalezeny!", "src_not_exist": "Zdrojová složka neexistuje!", "col_sel": "VÝBĚR BARVY", "hex_prompt": "Zadejte HEX kód barvy (např. #ff8c00)",
        "hex_empty": "Nebo nechte prázdné a stiskněte Enter pro Windows paletu.", "your_choice": "Vaše volba: ", "new_pref": "Nový text prefixu: ",
        "type_ext": "Napište koncovku (s tečkou):", "err_trans": "CHYBA PŘEKLADU", "skip_key": "Přeskočit klíč (Vložit prázdné)", "cancel_trans": "Zrušit překládání",
        "try_again": "Zkusit znovu", "change_api": "Změnit překladač", "win_title": "ZeddiHub Translator - Přehled Souborů", "tgt_lang_q": "ZVOLTE JAZYK ZDROJE PRO TUTO SLOŽKU",
        "dlg_src": "Vyberte prosím složku, ze které chcete čerpat soubory", "dlg_tgt": "Vyberte prosím cílovou složku pro překlady",
        "dlg_log": "Vyberte prosím složku pro ukládání logů", "dlg_bak": "Vyberte prosím složku pro ukládání záloh", "warn_nojson": "VAROVÁNÍ: Složka neobsahuje žádné .json soubory!",
        "warn_badjson": "VAROVÁNÍ: Vadné .json soubory (přeskočeny):", "api_req": "Zadejte API klíč:", "cfm_save": "[D/Enter] Potvrdit a uložit", "cfm_discard": "[A/Esc] Zahodit a zrušit"
    },
    "en": {
        "welcome": "Welcome to ZeddiHub Translator", "quote": "Everyone is good, but with us the best!",
        "main_menu": "MAIN MENU", "m_run": "Start Bulk Translation", "m_sel": "Selective Translation",
        "m_prefix": "Prefix Manager", "m_settings": "Settings", "m_folders": "Folder Overview", 
        "m_cleanup": "Cleanup Folders", "m_credits": "Credits & Links", "m_exit": "Exit", 
        "d_run": "Starts bulk translation for all files.", "d_sel": "Search a phrase and translate it manually/auto.",
        "d_prefix": "Configure prefix (colors, text, brackets).", "d_settings": "Paths, formats, API, language, post-action.",
        "d_folders": "Browse generated language folders.", "d_cleanup": "Delete target folders.",
        "d_credits": "Web, Discord, Banlist, Version.", "d_src": "Folder with original texts.", "d_tgt": "Folder to save translations.",
        "d_langs": "Select target languages.", "d_fmt": "Change file extension (.json, .txt...).",
        "d_api": "Choose engine (Recommended, Google, DeepL) and set API.", "d_sys": "Logs, Backups, Speed, Post-Action.",
        "d_ui": "Language of this application (CZ/EN).", "d_reset": "Delete config and hard reset the program.",
        "footer": "[W/S] Move | [D] Select | [A] Back | [Q] Menu", "yes": "YES", "no": "NO", 
        "confirm": "SUMMARY BEFORE START", "done": "TASK SUCCESSFULLY COMPLETED!",
        "clean_empty": "Nothing to clean. Target folders are empty.",
        "no_folders": "Folders do not exist yet.", "abort": "TRANSLATION ABORTED BY USER.",
        "wiz_title": "ZEDDIHUB TRANSLATOR FIRST SETUP", "wiz_step1": "STEP 1: UI LANGUAGE",
        "wiz_step2": "STEP 2: SOURCE FOLDER", "wiz_step2b": "STEP 3: SOURCE LANGUAGE",
        "wiz_step3": "STEP 4: TARGET FOLDER", "wiz_step4": "STEP 5: TRANSLATOR ENGINE",
        "wiz_step5": "STEP 6: FILE FORMAT", "wiz_step6": "STEP 7: LOGS AND BACKUPS",
        "use_def": "Use default folder in zeddihub_translator", "retry": "Try selecting again",
        "err_title": "FATAL PROGRAM ERROR", "err_m": "Return to Main Menu", "err_e": "Exit Application", "err_r": "Factory Reset (Delete config and restart)",
        "pause_title": "TRANSLATION PAUSED", "resume": "Resume Translation", "m_exit_menu": "Abort to Main Menu",
        "o_speed": "Visual Speed", "reset_def": "Restore default settings", "restarting": "RESTARTING APPLICATION...",
        "exit_q_title": "DO YOU REALLY WANT TO EXIT THE APP?", "clean_q_title": "DO YOU REALLY WANT TO DELETE THESE FOLDERS?",
        "v_close": "[A/Esc/Q] Close file viewer | [T] Translate this phrase", "inp_esc": "(You can paste using Ctrl+V or press ESC to cancel)",
        "sel_src_q": "SOURCE FOLDER FOR SEARCH", "sel_src_def": "Use current folder from Settings", "sel_src_new": "Select a different folder",
        "search_phrase": "Enter phrase to search (ignores colors and tags):", "search_res": "SEARCH RESULTS (Select match)",
        "found_keys": "KEYS FOUND IN", "choose_act": "CHOOSE TRANSLATION ACTION",
        "act1": "Bulk Auto-translate (All languages)", "act2": "Auto-translate (Only 1 selected language)",
        "act3": "Bulk Custom translate (All languages)", "act4": "Custom translate (Only 1 selected language)",
        "orig_t": "ORIGINAL TEXT", "new_t": "New text:", "sel_lang": "SELECT TARGET LANGUAGE FOR THIS ACTION",
        "auto_res": "TRANSLATION PREVIEW", "save_cont": "Saving and continuing...",
        "conn_lost": "Connection lost or API Rate Limit! Waiting 5s and trying again...",
        "pm_d1": "Enable prefix injection.", "pm_d2": "Text injected before message.", "pm_d3": "Click to set HEX or use palette.", "pm_d4": "Brackets and detection.",
        "pm_a1": "Enclose prefix in [ ].", "pm_a2": "Use the exact same color as prefix text.", "pm_a3": "Bracket color (HEX/Palette).", "pm_a4": "Delete old prefixes from files.",
        "post_action": "After Completion", "pa_none": "Nothing", "pa_exit": "Exit Application", "pa_sleep": "Sleep Mode", "pa_shutdown": "Shutdown PC",
        "empty_file": "Empty file", "detail": "KEY DETAIL", "folder_q": "SELECT TARGET FOLDER FOR THIS TRANSLATION",
        "f_config": "Use target folder from Settings", "f_new": "Select a different target folder", "no_phrase": "Phrase not found in any file.",
        "no_files": "No files found!", "src_not_exist": "Source folder does not exist!", "col_sel": "COLOR SELECTION", "hex_prompt": "Enter HEX color code (e.g. #ff8c00)",
        "hex_empty": "Or leave empty and press Enter for Windows palette.", "your_choice": "Your choice: ", "new_pref": "New prefix text: ",
        "type_ext": "Type extension (with dot):", "err_trans": "TRANSLATION ERROR", "skip_key": "Skip key (Insert empty)", "cancel_trans": "Cancel translation",
        "try_again": "Try again", "change_api": "Change translator", "win_title": "ZeddiHub Translator - File Overview", "tgt_lang_q": "SELECT SOURCE LANGUAGE FOR THIS FOLDER",
        "dlg_src": "Please select the source folder to read files from", "dlg_tgt": "Please select the target folder for translations",
        "dlg_log": "Please select the folder to save logs", "dlg_bak": "Please select the folder to save backups", "warn_nojson": "WARNING: Folder contains no .json files!",
        "warn_badjson": "WARNING: Corrupted .json files (skipped):", "api_req": "Enter API Key:", "cfm_save": "[D/Enter] Confirm and Save", "cfm_discard": "[A/Esc] Discard and Cancel"
    }
}