L = {
    "cz": {
        "welcome": "Vítej v ZeddiHub Server Status",
        "quote": "Monitoruj své servery v reálném čase!",
        "main_menu": "HLAVNÍ MENU",
        "m_dashboard": "Server Dashboard",
        "m_add": "Přidat Server",
        "m_remove": "Odebrat Server",
        "m_settings": "Nastavení",
        "m_credits": "Credits a Odkazy",
        "d_dashboard": "Zobrazit stav všech serverů v reálném čase.",
        "d_add": "Přidat nový server do seznamu pro monitoring.",
        "d_remove": "Odebrat server ze seznamu.",
        "d_settings": "Jazyk, obnovovací interval, tovární reset.",
        "d_credits": "Web, Discord, ZeddiS.",
        "wiz_title": "PRVOTNÍ INSTALACE SERVER STATUS",
        "wiz_step1": "KROK 1: JAZYK APLIKACE",
        "wiz_step2": "KROK 2: PŘIDEJTE PRVNÍ SERVER",
        "wiz_step3": "KROK 3: INTERVAL OBNOVOVÁNÍ",
        "footer": "[W/S] Pohyb | [D/Enter] Vybrat | [A/Esc] Zpět",
        "yes": "ANO", "no": "NE",
        "exit_q_title": "OPRAVDU CHCETE OPUSTIT SERVER STATUS?",
        "reset_def": "Tovární Reset a smazání configu",
        "srv_name": "Název",
        "srv_map": "Mapa",
        "srv_players": "Hráči",
        "srv_ping": "Ping",
        "srv_game": "Hra",
        "srv_offline": "OFFLINE",
        "srv_online": "ONLINE",
        "srv_timeout": "TIMEOUT",
        "srv_querying": "Dotazuji se...",
        "add_ip": "IP adresa serveru (např. 185.25.60.1): ",
        "add_port": "Port (výchozí 27015): ",
        "add_label": "Název/štítek (volitelné): ",
        "remove_confirm": "Opravdu odebrat tento server?",
        "no_servers": "Žádné servery v seznamu. Přidejte server přes hlavní menu.",
        "refreshing": "Obnovování...",
        "refresh_interval": "Interval obnovování (sekundy)",
        "last_refresh": "Poslední obnova"
    },
    "en": {
        "welcome": "Welcome to ZeddiHub Server Status",
        "quote": "Monitor your servers in real time!",
        "main_menu": "MAIN MENU",
        "m_dashboard": "Server Dashboard",
        "m_add": "Add Server",
        "m_remove": "Remove Server",
        "m_settings": "Settings",
        "m_credits": "Credits & Links",
        "d_dashboard": "View all server statuses in real time.",
        "d_add": "Add a new server to the monitoring list.",
        "d_remove": "Remove a server from the list.",
        "d_settings": "Language, refresh interval, factory reset.",
        "d_credits": "Web, Discord, ZeddiS.",
        "wiz_title": "ZEDDIHUB SERVER STATUS FIRST SETUP",
        "wiz_step1": "STEP 1: UI LANGUAGE",
        "wiz_step2": "STEP 2: ADD YOUR FIRST SERVER",
        "wiz_step3": "STEP 3: REFRESH INTERVAL",
        "footer": "[W/S] Move | [D/Enter] Select | [A/Esc] Back",
        "yes": "YES", "no": "NO",
        "exit_q_title": "DO YOU REALLY WANT TO EXIT?",
        "reset_def": "Factory Reset and clear config",
        "srv_name": "Name",
        "srv_map": "Map",
        "srv_players": "Players",
        "srv_ping": "Ping",
        "srv_game": "Game",
        "srv_offline": "OFFLINE",
        "srv_online": "ONLINE",
        "srv_timeout": "TIMEOUT",
        "srv_querying": "Querying...",
        "add_ip": "Server IP address (e.g. 185.25.60.1): ",
        "add_port": "Port (default 27015): ",
        "add_label": "Name/label (optional): ",
        "remove_confirm": "Really remove this server?",
        "no_servers": "No servers in list. Add a server from the main menu.",
        "refreshing": "Refreshing...",
        "refresh_interval": "Refresh interval (seconds)",
        "last_refresh": "Last refresh"
    }
}
