<script lang="ts">
  import { Save, Trash2, Keyboard } from "lucide-svelte";
  import Card from "$components/ui/Card.svelte";
  import Button from "$components/ui/Button.svelte";
  import BindDialog from "$components/panels/keybind/BindDialog.svelte";
  import { KEYBOARD_ROWS, type Game } from "$lib/data/keyboard";
  import { saveCfgFile } from "$api/saveFile";

  let {
    game,
    title,
  }: {
    game: Game;
    title: string;
  } = $props();

  // key name → bind command
  let binds = $state<Record<string, string>>({});

  let dialogOpen = $state(false);
  let dialogKeyName = $state("");
  let dialogCurrent = $state("");
  let saveStatus = $state("");

  const KEY_W = 38;
  const KEY_H = 34;
  const GAP = 4;

  function openBindFor(keyName: string) {
    dialogKeyName = keyName;
    dialogCurrent = binds[keyName] ?? "";
    dialogOpen = true;
  }

  function onResult(cmd: string | null) {
    if (cmd === null) {
      // remove
      const { [dialogKeyName]: _, ...rest } = binds;
      binds = rest;
    } else if (cmd) {
      binds = { ...binds, [dialogKeyName]: cmd };
    }
  }

  function clearAll() {
    binds = {};
  }

  async function saveCfg() {
    saveStatus = "";
    const entries = Object.entries(binds);
    if (entries.length === 0) {
      saveStatus = "✗ Žádné bindy nejsou definované";
      return;
    }
    let content = `// ${game.toUpperCase()} Keybind Config - Generated by ZeddiHub Tools\n// https://zeddihub.eu\n\n`;
    for (const [key, cmd] of entries) {
      // Lowercase + cleanup of internal aliases (Source key names use lowercase mostly)
      const k = key.toLowerCase();
      content += `bind "${k}" "${cmd}"\n`;
    }
    content += `\necho "[ZeddiHub] ${entries.length} bindů načteno"\n`;
    try {
      const path = await saveCfgFile(content, {
        defaultName: `${game}_keybinds.cfg`,
        title: `Uložit ${game} keybinds`,
      });
      if (path) saveStatus = `✓ Uloženo: ${path} (${entries.length} bindů)`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }

  let bindList = $derived(Object.entries(binds));
</script>

<div class="px-8 py-6 max-w-[1400px] mx-auto">
  <h1 class="text-3xl font-bold mb-1">{title}</h1>
  <p class="text-zh-text-muted text-sm mb-5">Klikni na klávesu a vyber příkaz z katalogu nebo zadej vlastní.</p>

  <Card class="mb-3" padding={4}>
    <div class="flex items-center gap-2 mb-2 text-xs text-zh-text-muted">
      <Keyboard size={14} />
      <span>Vizuální klávesnice — klikni na klávesu pro nastavení bindu</span>
    </div>

    <!-- Keyboard -->
    <div class="bg-black/30 rounded-card p-3 overflow-x-auto">
      <div class="inline-block">
        {#each KEYBOARD_ROWS as row, ri}
          <div class="flex" style="gap: {GAP}px; margin-bottom: {ri < KEYBOARD_ROWS.length - 1 ? GAP : 0}px;">
            {#each row as k}
              {@const isBound = !!binds[k.name]}
              <button
                type="button"
                class="rounded text-[10px] font-bold transition shrink-0"
                class:bg-zh-primary={isBound}
                class:text-zh-text-dark={isBound}
                class:bg-zh-card-bg={!isBound}
                class:hover:bg-zh-card-hover={!isBound}
                style="width: {k.w * KEY_W + (k.w - 1) * GAP}px; height: {KEY_H}px;"
                onclick={() => openBindFor(k.name)}
                title={isBound ? `${k.name}: ${binds[k.name]}` : k.name}
              >
                {k.label}
              </button>
            {/each}
          </div>
        {/each}
      </div>
    </div>
  </Card>

  <!-- Active binds list -->
  {#if bindList.length > 0}
    <Card class="mb-3">
      <h3 class="text-sm font-bold mb-2 flex items-center justify-between">
        Aktivní bindy ({bindList.length})
        <Button variant="ghost" onclick={clearAll} class="!h-6 text-[10px] !text-zh-error">
          <Trash2 size={10} />
          Vymazat vše
        </Button>
      </h3>
      <div class="font-mono text-[11px] space-y-0.5 max-h-48 overflow-auto">
        {#each bindList as [k, cmd]}
          <button
            type="button"
            class="w-full flex items-center gap-3 px-2 py-1 rounded hover:bg-zh-card-hover transition text-left"
            onclick={() => openBindFor(k)}
          >
            <span class="text-zh-primary w-32 shrink-0">bind "{k.toLowerCase()}"</span>
            <span class="text-zh-text flex-1 truncate">"{cmd}"</span>
          </button>
        {/each}
      </div>
    </Card>
  {/if}

  <Button variant="primary" onclick={saveCfg} class="w-full">
    <Save size={14} />
    Uložit {game} keybinds.cfg
  </Button>

  {#if saveStatus}
    <div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>
  {/if}
</div>

<BindDialog
  open={dialogOpen}
  onClose={() => (dialogOpen = false)}
  onResult={onResult}
  keyName={dialogKeyName}
  current={dialogCurrent}
  {game}
/>
