<script lang="ts">
  import { Save, Copy } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Card from "$components/ui/Card.svelte";
  import { saveCfgFile } from "$api/saveFile";
  import { writeText } from "@tauri-apps/plugin-clipboard-manager";

  // Mirror legacy rust.py:_build_binds (3 categories)
  const CATS: { title: string; binds: [string, string, string][] }[] = [
    {
      title: "Základní akce",
      binds: [
        ["mouse1", "Levá myš",         "attack"],
        ["mouse2", "Pravá myš",        "attack2"],
        ["r",      "Reload",            "reload"],
        ["f",      "Svítilna",          "lighttoggle"],
        ["g",      "Zahodit zbraň",    "drop"],
      ],
    },
    {
      title: "Pohyb & Přežití",
      binds: [
        ["space",      "Skok",          "jump"],
        ["lshift",     "Sprint",        "sprint"],
        ["lctrl",      "Dřep",          "duck"],
        ["e",          "Použít",        "use"],
        ["leftarrow",  "Lean doleva",   "+lean_left"],
        ["rightarrow", "Lean doprava",  "+lean_right"],
      ],
    },
    {
      title: "Chat & Info",
      binds: [
        ["t",          "Chat",       "chat.open"],
        ["backquote",  "Konzole",    "consoletoggle"],
        ["tab",        "Inventář",   "inventory.toggle"],
        ["m",          "Mapa",       "map.toggle"],
      ],
    },
  ];

  let values = $state<Record<string, string>>({});
  for (const c of CATS) for (const [k, _l, def] of c.binds) values[k] = def;
  let saveStatus = $state("");

  function buildLines(): string[] {
    const lines: string[] = [];
    for (const c of CATS) {
      for (const [k] of c.binds) {
        const v = values[k];
        if (v) lines.push(`bind ${k} "${v}"`);
      }
    }
    return lines;
  }

  async function copyAll() {
    saveStatus = "";
    const lines = buildLines();
    try {
      await writeText(lines.join("\n"));
      saveStatus = `✓ Zkopírováno ${lines.length} bindů — vlož do Rust konzole (F1)`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }

  async function saveCfg() {
    saveStatus = "";
    const lines = buildLines();
    let content = "// Rust Bindy - Generated by ZeddiHub Tools\n";
    content += "// Vlož příkazy do Rust konzole (F1) nebo souboru binds.cfg\n\n";
    content += lines.join("\n") + "\n";
    try {
      const path = await saveCfgFile(content, {
        defaultName: "rust_binds.txt",
        title: "Uložit binds.txt",
        filters: [
          { name: "Text", extensions: ["txt"] },
          { name: "Config", extensions: ["cfg"] },
          { name: "All", extensions: ["*"] },
        ],
      });
      if (path) saveStatus = `✓ Uloženo: ${path} (${lines.length} bindů)`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">Rust — Bindy</h3>
  <p class="text-xs text-zh-text-muted mb-3">Vygenerujte bind příkazy pro Rust konzoli (F1).</p>

  {#each CATS as c}
    <Card class="mb-3">
      <h4 class="text-sm font-bold text-zh-primary mb-2">{c.title}</h4>
      {#each c.binds as [key, label, _def]}
        <label class="grid grid-cols-[110px_140px_1fr] items-center gap-3 py-1.5 text-xs">
          <span class="font-mono text-zh-primary">[{key}]</span>
          <span class="text-zh-text-muted">{label}</span>
          <input type="text" bind:value={values[key]}
            class="bg-zh-card-hover border border-zh-border rounded-entry px-3 h-8 text-[11px] font-mono focus:outline-none focus:border-zh-primary" />
        </label>
      {/each}
    </Card>
  {/each}

  <div class="grid grid-cols-2 gap-2">
    <Button variant="secondary" onclick={copyAll}>
      <Copy size={14} />
      Kopírovat do schránky
    </Button>
    <Button variant="primary" onclick={saveCfg}>
      <Save size={14} />
      Uložit binds.txt
    </Button>
  </div>

  {#if saveStatus}<div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>{/if}
</div>
