<script lang="ts">
  import { Save } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Section from "$components/form/Section.svelte";
  import EntryRow from "$components/form/EntryRow.svelte";
  import { saveCfgFile } from "$api/saveFile";

  // Mirror legacy rust.py:_build_settings — 3 categories
  const CATS: { title: string; fields: [string, string, string, string][] }[] = [
    {
      title: "Grafika",
      fields: [
        ["graphics.quality", "Kvalita grafiky", "3",   "0=nejnižší, 5=nejvyšší"],
        ["grass.on",         "Tráva",           "true", "true/false"],
        ["terrain.quality",  "Terén",           "100",  "0–200"],
        ["water.quality",    "Voda",            "10",   "0–100"],
        ["shadowmode",       "Stíny",           "1",    "0=žádné, 1=nízké, 2=vysoké"],
        ["lodrange",         "LOD vzdálenost",  "200",  "100–2000"],
      ],
    },
    {
      title: "Zvuk",
      fields: [
        ["audio.master", "Master hlasitost", "1.0", "0.0–1.0"],
        ["audio.music",  "Hudba",            "0.0", ""],
        ["audio.game",   "Hra",              "1.0", ""],
        ["audio.voice",  "Hlas",             "1.0", ""],
      ],
    },
    {
      title: "Výkon",
      fields: [
        ["fps.limit",  "FPS limit",  "0", "0=neomezeno"],
        ["pool.mode",  "Pool mode",  "0", ""],
      ],
    },
  ];

  let values = $state<Record<string, string>>({});
  for (const c of CATS) for (const [k, _l, def] of c.fields) values[k] = def;
  let saveStatus = $state("");

  async function saveCfg() {
    saveStatus = "";
    let content = "// Rust Client Config - Generated by ZeddiHub Tools\n\n";
    for (const c of CATS) for (const [k] of c.fields) content += `${k} ${values[k]}\n`;
    try {
      const path = await saveCfgFile(content, {
        defaultName: "rust_client.cfg",
        title: "Uložit client.cfg",
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">Rust — Herní Nastavení & CFG</h3>
  <p class="text-xs text-zh-text-muted mb-3">Generátor `client.cfg` pro Rust.</p>

  {#each CATS as c}
    <Section title={c.title}>
      {#each c.fields as [k, label, _def, hint]}
        <EntryRow label={label} bind:value={values[k]} hint={hint || k} />
      {/each}
    </Section>
  {/each}

  <Button variant="primary" onclick={saveCfg} class="w-full mt-3">
    <Save size={14} />
    Uložit client.cfg
  </Button>

  {#if saveStatus}<div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>{/if}
</div>
