<script lang="ts">
  import { Save, FileCode } from "lucide-svelte";
  import Button from "$components/ui/Button.svelte";
  import Section from "$components/form/Section.svelte";
  import EntryRow from "$components/form/EntryRow.svelte";
  import { saveCfgFile } from "$api/saveFile";

  // Mirror legacy rust.py:_build_server_config (4 sections)
  const CATS: { title: string; fields: [string, string, string][] }[] = [
    {
      title: "Základní nastavení",
      fields: [
        ["server.hostname",    "Název serveru",      "ZeddiHub Rust Server"],
        ["server.description", "Popis serveru",      "ZeddiHub Rust Community"],
        ["server.url",         "URL webu",           "https://zeddihub.eu"],
        ["server.headerimage", "Header obrázek URL", ""],
        ["server.port",        "Port",               "28015"],
        ["server.level",       "Mapa",               "Procedural Map"],
        ["server.seed",        "Seed",               "12345"],
        ["server.worldsize",   "Velikost světa",     "4000"],
        ["server.maxplayers",  "Max hráčů",          "100"],
      ],
    },
    {
      title: "Výkon",
      fields: [
        ["server.tickrate", "Tick rate",      "30"],
        ["server.gc_mb",    "GC paměť (MB)",  "256"],
        ["server.netcache", "Net cache",      "4"],
        ["fps.limit",       "FPS limit",      "30"],
      ],
    },
    {
      title: "Herní pravidla",
      fields: [
        ["server.pve",              "PvE mód",           "false"],
        ["decay.scale",             "Decay rychlost",    "1.0"],
        ["server.radiation",        "Radiace",           "true"],
        ["server.airdropfrequency", "Airdrop frekvence", "0"],
      ],
    },
    {
      title: "Oxide / uMod",
      fields: [
        ["oxide.reload", "Reload příkaz", "oxide.reload *"],
        ["oxide.unload", "Unload příkaz", "oxide.unload *"],
      ],
    },
  ];

  let values = $state<Record<string, string>>({});
  for (const c of CATS) for (const [k, _l, def] of c.fields) values[k] = def;

  let saveStatus = $state("");

  async function saveCfg() {
    saveStatus = "";
    let content = "// Rust Server Config - Generated by ZeddiHub Tools\n\n";
    for (const c of CATS) for (const [k] of c.fields) {
      const v = values[k];
      if (v) content += `${k} "${v}"\n`;
    }
    try {
      const path = await saveCfgFile(content, {
        defaultName: "rust_server.cfg",
        title: "Uložit server.cfg",
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }

  async function saveBat() {
    saveStatus = "";
    const hn   = values["server.hostname"]   || "RustServer";
    const port = values["server.port"]       || "28015";
    const seed = values["server.seed"]       || "12345";
    const size = values["server.worldsize"]  || "4000";
    const maxp = values["server.maxplayers"] || "100";

    const content =
`@echo off
REM Rust Server Start Script - Generated by ZeddiHub Tools
RustDedicated.exe -batchmode ^^
  +server.port ${port} ^^
  +server.hostname "${hn}" ^^
  +server.worldsize ${size} ^^
  +server.seed ${seed} ^^
  +server.maxplayers ${maxp} ^^
  +server.saveinterval 600 ^^
  +rcon.port 28016 ^^
  +rcon.password changeme ^^
  -logfile "%DATE:~-4%-%DATE:~4,2%-%DATE:~7,2%.log"
`;
    try {
      const path = await saveCfgFile(content, {
        defaultName: "start_rust_server.bat",
        title: "Uložit server start script",
        filters: [
          { name: "Batch", extensions: ["bat"] },
          { name: "Shell", extensions: ["sh"] },
          { name: "All",   extensions: ["*"] },
        ],
      });
      if (path) saveStatus = `✓ Uloženo: ${path}`;
    } catch (e: any) {
      saveStatus = `✗ ${e?.message ?? e}`;
    }
  }
</script>

<div>
  <h3 class="text-lg font-bold text-zh-primary mb-1">Rust — Server Config Generátor</h3>
  <p class="text-xs text-zh-text-muted mb-3">Generátor `server.cfg` + start.bat skriptu pro RustDedicated.</p>

  {#each CATS as c}
    <Section title={c.title}>
      {#each c.fields as [k, label, _def]}
        <EntryRow label={label} bind:value={values[k]} hint={k} />
      {/each}
    </Section>
  {/each}

  <div class="grid grid-cols-2 gap-2 mt-3">
    <Button variant="primary" onclick={saveBat}>
      <Save size={14} />
      Generovat start.bat
    </Button>
    <Button variant="secondary" onclick={saveCfg}>
      <FileCode size={14} />
      Generovat server.cfg
    </Button>
  </div>

  {#if saveStatus}<div class="mt-2 text-xs text-zh-text-muted">{saveStatus}</div>{/if}
</div>
